

local t={}

function on_use_object(obj)
	(t[obj:section()] or function()end)()
end

t['mobile_changer'] = function()
	--level.start_stop_menu(_mobile_changer.mobile_changer(), true)
	--alife():create('mobile_changer', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())

	--db.actor:give_info_portion ("skidan_milnflash_info") -- появляется Феникс в вагончике
		--	if db.actor:dont_has_info("underbridge_task_sucess") then
		--		db.actor:give_info_portion ("underbridge_task_sucess") -- получаем доступ за ЖД путь и спавнятся патрули агентов везде
		--	end
	-- db.actor:give_info_portion ("malandrinus_body_task_finish")
	-- db.actor:give_info_portion ("musorka_monstr_finish")
	-- db.actor:give_info_portion ("skidan_post_stels_task")
	-- alife():create('mask_outfit', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	-- db.actor:give_info_portion ("dar_hunter_vorpal_info2") -- спавнятся Боря и Жора в ТД у фермы

	-- db.actor:give_info_portion ("weapon_powerup") -- получаем достижение "Оружейник"
	-- db.actor:give_info_portion ("arts_powerup") -- получаем достижение "Коллекционер"
	-- db.actor:give_info_portion ("esc_heli_crash_uncharged") -- выключается электра у вертушки на Кордоне
	-- db.actor:give_info_portion ("sickness") -- заболеваем чумой
	-- db.actor:give_info_portion ("bonebreak") -- получаем перелом
	-- alife():create('kamp_freezer_key', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id()) -- ключ от холодильника

	-- alife():create('garbage_key', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	-- addon_dialogs.spawn_test_changer()

	--db.actor:give_info_portion ("spawn_garbage_companions") -- спавнятся Андрей с майором на Свалке
	db.actor:give_info_portion ("garbage_door_opened")

	-- level.set_weather("test",true)
	-- db.actor:give_info_portion ("garb_cargo_heli_goto_place") -- вылетает грузовая вертушка на Свалке
	--db.actor:give_money(500000)
	-- db.actor:give_info_portion ("hunter2_deadly_wind_info")
	-- db.actor:give_info_portion ("cristall_receiver1_shield_off")

	-- db.actor:give_info_portion ("sanya_food_task_finish")

	-- db.actor:give_info_portion ("underbridge_task_fail") -- мы не успели проскочить сквозь "Железку"(для проверки квеста по стелс-прохождению блокпоста)

	-- db.actor:give_info_portion ("skidan_killers_info") -- Квест "Жертвоприношение"

	-- starvation.add_karma(-0.1)

	-- db.actor:give_info_portion ("dar_farm_deadzone_off") -- разряжаем захоронение на ферме в ТД

	 -- db.actor:give_info_portion ("dar_hunter_vorpal_info") -- спавнится первая часть дневника Ворпала в палатке(Долина)

	-- db.actor:give_info_portion ("dar_trap_teleport1_dead") -- можно выйти из телепорта-ловушки в Долине
	-- db.actor:give_info_portion ("dar_trap_teleport2_dead")
	-- db.actor:give_info_portion ("dar_trap_teleport3_dead")

	-- db.actor:give_info_portion ("actor_find_dar_woman") -- мы оказываемся в телепорте-довушке в Долине

	-- xr_effects.mark_water_and_sleep_places()

	-- db.actor:give_info_portion ("repare_btr_task") -- Квест "С ветерком"(найти редуктор)

		--if db.actor:dont_has_info("dyatlov_group_task") then
		--	db.actor:give_info_portion ("dyatlov_group_task") -- Квест "Смерть, идущая по следу"(группа Дятлова)
		--end

	-- db.actor:give_info_portion ("garb_deadzone_off") -- разряжаем захоронение на Свалке

	-- addon_dialogs.mark_bobik()
	-- db.actor:give_info_portion ("find_instruments_task") -- квест на инструменты

	-- db.actor:give_info_portion ("ochkaric_shron_info") -- квест на "Смерть-лампу"
	-- db.actor:give_info_portion ("deadman_head_powerup") -- достижение "Чёрный копатель"
	-- db.actor:give_info_portion ("yuriy_germetic_suit_done") -- в подземке Агро начинается квест с Юрием
	-- db.actor:give_info_portion ("spawn_agr_redrik2") -- спавнится второй Шухарт у выхода из подземки Агро

	-- db.actor:give_info_portion ("atp_controler_task") -- Квест убить контролёра на АТП

	--db.actor:give_info_portion ("dar_build_guards_spawn") -- спавнится вся кагала хэдхантеров в недостройке в ТД
	--db.actor:give_info_portion ("hunter4_goto_koridor")	--	чтобы сработала растяжка
	--alife():create('af_hive', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())

	-- db.actor:give_info_portion ("x18_codedoor2_open")
	-- db.actor:give_info_portion ("dar_oboroten_task") -- задание на убийство оборотня в ТД
	
	-- db.actor:give_info_portion ("dar_hunter_afterlab_meet") -- разговор с Серегой после х-18

	-- db.actor:give_info_portion ("dar_abdul_off") -- спавнится Абдуль на Свалке

	--db.actor:give_info_portion ("hunter2_repare_btr") -- появляется возможность проехать на БТР-е в Бар

	-- db.actor:give_info_portion ("bar_abdul_sick")

	--alife():create('wonder_doll', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--db.actor:give_info_portion ("wonderdoll_first_talk")
	
	--addon_dialogs.garbage_companions_start()
	--addon_dialogs.spawn_bar_ventil3()
	--db.actor:give_info_portion ("abdul_goto_military")
	--db.actor:give_info_portion ("bar_virus_off")
	--xr_effects.spawn_bar_to_mil_lchanger()
	--db.actor:give_info_portion ("mil_abdul_spawn") -- спавнится Абдуль на Милитари
	
	--db.actor:give_info_portion ("sanya_suslik_task") -- условие для спавна призраков Суслика и Дыма на Ростке
	--db.actor:give_info_portion ("stalker_smoke_task") -- условие для спавна призраков Суслика и Дыма на Ростке
	
	--db.actor:give_info_portion ("yan_burer_sold9_dead")	--	добро пожаловать к бюрерам
	--db.actor:give_info_portion ("yan_burer_sold10_dead")
	--db.actor:give_info_portion ("yan_burer_sold11_dead")
	--addon_dialogs.release_yan_zavod_guard_burers()
	
	--db.actor:give_info_portion ("x16_adviser_walk2")	--	перед первым разговором с Сахаровым
	--db.actor:give_info_portion ("x16_brain_temperature")	--	перед разговором с Мозгом
	--db.actor:give_info_portion ("yan_goto_lab")
	--alife():create('x16_documents2', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	
	--db.actor:give_info_portion ("x16_fuel_blow")	--	 после того, как выбрались из Х-16 с Сахаром
	
	--db.actor:give_info_portion ("yan_saharov_escape")
	--db.actor:give_info_portion ("saharov_flash_task")
	--alife():create('ros_hunters_flash', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--db.actor:give_info_portion ("yan_sold_comander_reward")	--	 можно идти в бункер к Сахарову
	
	
	--db.actor:give_info_portion ("turrets_shoot_on")	--	все турели включаются
	
	--db.actor:give_info_portion ("spawn_ros_desant")
	--db.actor:give_info_portion ("ros_hunter_behind_rescuer2")
	--db.actor:give_info_portion ("ros_rescuer_talk1")	--	разведчик с Ростка может бежать к вертолёту
	--db.actor:give_info_portion ("lenin_bust_destroyed")	--	разбили Ленина
	--db.actor:give_info_portion ("lenin_bust_gathered")	--	забрали Ленина
	--db.actor:give_info_portion ("ros_tunnel_acess")	--	открываются ворота на Ростке
	
	--db.actor:give_info_portion ("saharov_medbox_ready")	--	активируется Личный доктор
	
	--alife():create('vint', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	
	--alife():create('af_scale', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_ballast', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_steel_nut', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_sagebrush', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_lens', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_hole', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	
	--db.actor:give_info_portion ("abdul_goto_military")	--	спавнится Абдуль на Милитари
	
	--db.actor:give_info_portion ("mil_freak_water_drink")	--	попадаем на деревню к Дедушке(Милитари)
	--db.actor:give_info_portion ("mil_ded_house_find")
	
	--db.actor:give_info_portion ("rad_abdul_spawn")	--	спавнится Абдуль на Радаре
	
	--db.actor:give_info_portion ("x10_button_switch")	--	спавнится Абдуль в Припяти
	
	--db.actor:give_info_portion ("rad_abdul_lost")	--	задание освободить Абдуля из подземелья
	
	--db.actor:give_info_portion ("pri_avtostation_task")	--	убить кровососа на автостанции в Припяти
	
	--db.actor:give_info_portion ("pri_agents_meet_task")	--	встретится с лидером агентов в Припяти
	
	--alife():create('pri_analog_chip', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	--alife():create('af_deadmask_2', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	
	--addon_2.damage_actor_all_body()
	--db.actor:give_info_portion ("mil_deadsold1_info")
	
	--db.actor:give_info_portion ("predb_rpg_info")
	
	--xr_effects.karma_up()
	
	--db.actor:give_info_portion ("mil_aviators_rwrd2")	-- можно идти разряжать грави-аномалию на Милитари;
	

	
end







t['bomba'] = function()
addon.actor_disable_inventory()
news_manager.send_tip(db.actor, "bomba_use_tip", nil, "stalker", 3000, nil)
local pos = db.actor:position()
alife():create("script_bomb", vector():set(pos.x+1, pos.y, pos.z), db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

t['bomba_big'] = function()
addon.actor_disable_inventory()
news_manager.send_tip(db.actor, "bomba_use_tip", nil, "stalker", 3000, nil)
local pos = db.actor:position()
alife():create("script_bomb_big", vector():set(pos.x+1, pos.y, pos.z), db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

t['detonator'] = function()
for i=1,65534 do
local bomb = level.object_by_id(i)
local pos = db.actor:position()
	if bomb and ( bomb:section() == "script_bomb" or bomb:section() == "script_bomb_big" ) and bomb:position():distance_to(pos)<100 then
		local h=hit()
		h.type = hit.fire_wound
		h.power = 10.0
        h.impulse = 0
        h.draftsman = db.actor
        h.direction = vector():set(0,0,0)
        bomb:hit(h)
			addon.actor_disable_inventory()
			soundtrack.beep1()
	end
end
end


t['ruined_docs'] = function()
	local obj = level_object_by_sid(8977)
	if obj and obj ~= nil and obj:position():distance_to(db.actor:position()) < 5 then
		addon.ruined_docks_using()
		addon.actor_disable_inventory()
	end
end

t['anomal_lamp'] = function()
local sim = alife()
	if ( addon_utils.get_object_number(db.actor, "af_lens") == 3 ) then
		addon.actor_disable_inventory()
		local sobj = sim:create("anomal_lamp_static", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
		sim_assign_story_id(sobj.id, story_ids.anomal_lamp_static)
		addon.remove_items("af_lens", 3)
		addon.remove_items("anomal_lamp", 1)
	elseif ( addon_utils.get_object_number(db.actor, "af_lens") < 3 ) then
		addon.actor_disable_inventory()
		soundtrack.actor_anomal_lamp_use()
	end
end


t['signs_albom'] = function()
	if db.actor:dont_has_info("sssr_sgns_bonus") then
		addon_devices.signs_album_start()
	elseif has_alife_info("sssr_sgns_bonus") then
		addon_devices.signs_album_start2()
	end
end

t['anomal_conserva'] = function()
local text = "Ярость"
	if db.actor:dont_has_info("rage2") then
		db.actor:give_info_portion ("rage2")
		start_real_timer(120, "timer_actions.anomal_conserva_timer_action")
	end
	db.actor.power = 0.5
	db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	soundtrack.actor_rage_snd()
end

t['radiation_liquor'] = function()
local text = "Иммунитет к радиации"
	amk.spawn_item_in_inv("flyaga_empty")
	db.actor:disable_info_portion("rad_seek")
	if db.actor:dont_has_info("rad_immunity") then
		db.actor:give_info_portion ("rad_immunity")
		start_real_timer(1000, "timer_actions.radiation_liquor_timer_action")
	end
	db.actor.power = 0.2
	db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
end

t['power_liquor'] = function()
local text = "Бодрость"
	amk.spawn_item_in_inv("flyaga_empty")
	db.actor:give_info_portion ("tea_effect")
	start_real_timer(900, "timer_actions.teapot_timer_action")
	db.actor.power = 1.0
	db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
end

t['rage_liquor'] = function()
if db.actor:dont_has_info("rage") then
	db.actor:give_info_portion ("rage")
	start_real_timer(900, "timer_actions.rage_timer_action")
end
end

t['brain_liquor'] = function()
if db.actor:dont_has_info("cat_effect") then
	db.actor:give_info_portion ("cat_effect")
	start_real_timer(900, "timer_actions.cat_effect_timer_action")
end
end


t['pri_anomal_ball'] = function()
start_real_timer(1, "timer_actions.pri_anomal_ball_use_action")
addon.actor_disable_inventory()
end

t['af_pult'] = function()
	db.actor:give_info_portion ("af_pult_use")
	addon.actor_disable_inventory()
	soundtrack.glass_break()
	start_real_timer(2, "timer_actions.af_pult_broken_action")
	local st = get_hud():GetCustomStatic("af_pult_destroyed") or get_hud():AddCustomStatic("af_pult_destroyed",true)
	st.m_endTime = time_global()/1000 + 7
end

t['mil_raciya'] = function()
if ( db.actor:dont_has_info("mil_separ_acess") and db.actor:dont_has_info("mil_vsu_acess") ) then
	local level_name = level.name()
	if level_name == "l07_military" then
		addon_devices.mil_raciya_start()
		soundtrack.raciya_sound()
	end
end
end

t['mil_electron_pribor'] = function()
	if ( xr_conditions.actor_in_mil_village_tower_roof_zone() == true and has_alife_info("mil_village_antenna_task") and db.actor:dont_has_info("mil_icon_finded") ) then
		addon.actor_disable_inventory()
		db.actor:hide_weapon()
		db.actor:give_info_portion ("mil_pribor_on")
		start_real_timer(6, "timer_actions.mil_electron_pribor_action")
		soundtrack.click()
	end
end

t['mil_hatchet'] = function()
	if xr_conditions.actor_behind_mil_village_shkaf() == true then
		level.add_pp_effector("agr_u_fade.ppe", 2107, false)
		start_real_timer(3, "timer_actions.mil_village_shkaf_action")
		addon.remove_items("mil_hatchet", 1)
	end
end



t['mil_freak_water'] = function()
start_real_timer(2, "timer_actions.mil_freak_water_action1")
end



t['matras'] = function()
sleep_manager.use_matras()
end

t['medkomplekt'] = function()
addon_devices.medkomplekt_use()
end


t['mre_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['irp-b_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['bread_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['syrok_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['kolbasa_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['conserva_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['salo_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['conserva2_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end

t['kefir_bad'] = function()
if not inventory.belt["af_bottle"] then
	addon.actor_disable_inventory()
	level.disable_input()
	db.actor:hide_weapon()
	level.add_pp_effector("deadcity_wake.ppe", 2007, false)
	start_real_timer(3, "timer_actions.intoxication_effect1")
end
end



t['yan_sergant_rope'] = function()
	if xr_conditions.actor_behind_yan_zavod_zone() == true then
		start_real_timer(5, "timer_actions.yan_sergant_rope_action")
		level.add_pp_effector("agr_u_fade.ppe", 2107, false)
		addon.actor_disable_inventory()
		db.actor:hide_weapon()
		addon.remove_items("yan_sergant_rope", 1)
	end
	if xr_conditions.actor_behind_yan_zavod_zone() ~= true then 
		news_manager.send_tip(db.actor, "kazarma_door_too_far", nil)
	end
end

t['yan_sold_raciya'] = function()
	if ( xr_conditions.actor_in_zone(nil,nil,{"yan_zavod_sold_raciya_zone"}) and db.actor:dont_has_info("yan_sold_raciya_info") ) then
		addon_devices.yan_sold_raciya_start()
		soundtrack.raciya_sound()
	end
	if has_alife_info("yan_sold_raciya_info") then 
		soundtrack.raciya_sound()
	end
end

t['boarleg_soup'] = function()
soundtrack.gg_self_made_food_eat()
end

t['flesheye_soup'] = function()
soundtrack.gg_self_made_food_eat()
end

t['pseudotail_soup'] = function()
soundtrack.gg_self_made_food_eat()
end

t['krovosos_soup'] = function()
soundtrack.gg_self_made_food_eat()
end

t['tushkano_soup'] = function()
soundtrack.gg_self_made_food_eat()
end



t['antirad'] = function()
if xr_conditions.actor_wears_smuggler_outfit() == true then
local rad = db.actor.radiation
	if rad > 0.002 then
		db.actor.radiation = rad - 0.3
	end
end
if has_alife_info("rad_seek") then
	news_manager.send_tip(db.actor, "rad_seek_antirads_use_tip", nil, "anomal", 7000, nil)
end
end


t['vodka'] = function()
local psy = db.actor.psy_health
db.actor.psy_health = psy + 0.2
	if xr_conditions.actor_wears_forester_outfit() == true then
		addon.kefir_autouse()
	end
	if db.actor:object("af_drink") ~= nil then
	local hlth = db.actor.health
		if hlth < 1 then
			db.actor.health = 1.0
		end
	end
end

t['medkit'] = function()
if xr_conditions.actor_wears_forester_outfit() == true then
local hlth = db.actor.health
db.actor.health = hlth + 0.3
end
end

t['medkit_army'] = function()
if xr_conditions.actor_wears_forester_outfit() == true then
local hlth = db.actor.health
db.actor.health = hlth + 0.3
end
end

t['medkit_scientic'] = function()
if xr_conditions.actor_wears_forester_outfit() == true then
local hlth = db.actor.health
db.actor.health = hlth + 0.3
end
end

t['bandage'] = function()
if xr_conditions.actor_wears_forester_outfit() == true then
alife():create('bandage', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
db.actor:eat(db.actor:object("bandage"))
end
end

t['otrezvin'] = function()
local psy = db.actor.psy_health
db.actor.psy_health = psy + 0.3
end


t['ros_house_keis'] = function()
local text = "Получен предмет: ключ директора"
addon.actor_disable_inventory()
db.actor:give_info_portion("ros_house_keis_info")
alife():create('ros_director_key', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
end


t['guitar_f'] = function()
db.actor:hide_weapon()
addon.actor_disable_inventory()
soundtrack.guitar_use()
start_real_timer(17, "timer_actions.guitar_play_timer_action", "guitar_play_timer")
end


t['sigarets'] = function()
local text = "Нечем прикурить"
local pos = db.actor:position()
local fx_particle = "industrial_particles\\exhaust_isparenie_00"
	if ( db.actor:object("matches") ~= nil or db.actor:object("lighter") ~= nil or has_alife_info("arts_powerup_fire") ) then
			--if timer_exists("pain_timer") then
			--	get_timer("pain_timer"):remove()
			--end
			if inventory.belt["af_sigarets"] then
				local hlth = db.actor.health
				if hlth < 1 then
					db.actor.health = 0.2
				end
			end
		db.actor.power = -0.1
		soundtrack.actor_smoking()
		db.actor:disable_info_portion("pain")
		addon.remove_items("sigarets", 1)
		fx_particle = particles_object(fx_particle)
		fx_particle:play_at_pos(pos)
		addon.actor_disable_inventory()
	elseif ( db.actor:object("matches") == nil or db.actor:object("lighter") == nil or db.actor:dont_has_info("arts_powerup_fire") ) then
		db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	end
end


t['camerer_box'] = function()
	amk.remove_item(db.actor:object("camerer_box"))
	soundtrack.open_box()
	db.actor:give_info_portion ("wonder_task_done7")
	news_manager.send_tip(db.actor, "agr_camerer_box_info_tip", nil, "info", 12000, nil)
	amk.spawn_item_in_inv("camerer_docks")
end


t['cheburashka'] = function()
addon.actor_disable_inventory()
soundtrack.cheburashka_use()
if xr_conditions.actor_see_bar_karlik() == true then
		if db.actor:dont_has_info("bar_karlik_chebur_done") then
			db.actor:give_info_portion ("bar_karlik_chebur_done")
			addon.remove_items("cheburashka", 1)
			amk.spawn_item_in_inv("bar_vakcine_ballon")
			news_manager.send_tip(db.actor, "bar_vakcine_ballon_finded_tip", nil)
		end
end
end


t['af_watch'] = function()
db.actor:give_info_portion ("af_watch_used")
addon.actor_disable_inventory()
ogsm_anomaly.del_anomaly2()
amk.spawn_item_in_inv("af_watch_empty")
	-- amk.g_start_timer("watch",0,1,0)
	start_real_timer(1800, "timer_actions.watch_timer_action")
	xr_effects.karma_down()
end

t['af_top'] = function()
addon.actor_disable_inventory()
local sim = alife()
local sobj = alife():create("af_top_static", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
sim_assign_story_id(sobj.id, story_ids.af_top)
addon_dialogs.spawn_af_top_zone()
end

t['bar_raciya'] = function()
	if db.actor:dont_has_info("bar_infection_info") then
		addon_devices.bar_raciya_start()
		soundtrack.raciya_sound()
	end
	if has_alife_info("bar_infection_info") then 
		soundtrack.raciya_sound()
	end
end

t['tirsa_pda'] = function()
	if db.actor:dont_has_info("garb_tirsa_killed_by_actor") then 	-- заложники д.б. живые
		db.actor:give_info_portion ("tirsa_pda_info")
		addon_dialogs.mark_garb_hostage()
		news_manager.send_tip(db.actor, "dyatlovs_man_pda_info_text", nil, "info", 6000, nil)
		addon.actor_disable_inventory()
	elseif has_alife_info("garb_tirsa_killed_by_actor") then 	-- заложники д.б. мертвые
		db.actor:give_info_portion ("tirsa_pda_info")
		db.actor:give_info_portion ("garb_hostages_kill")
		addon_dialogs.spawn_reketirs_assistant1()
		addon.actor_disable_inventory()
		addon_dialogs.mark_garb_hostage()
		news_manager.send_tip(db.actor, "dyatlovs_man_pda_info_text", nil, "info", 6000, nil)
	end
end

t['magnitofon_portable'] = function()
	addon_devices.magnitofon_interface()
end

t['anomal_radio'] = function()
	alife():create('script_radio', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	alife():create('script_radio_point', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	-- db.actor:give_info_portion ("anomal_radio_play")
end

t['t_akumulator1'] = function()
if ( db.actor:dont_has_info("teleport_part_indtalled") and xr_conditions.actor_wears_headhunter_outfit() == true ) then
	local sim = alife()
	local sobj = sim:create("t_point", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
	sim_assign_story_id(sobj.id, story_ids.t_point)
		addon.actor_disable_inventory()
		amk.spawn_item_in_inv("t_akumulator2")
		db.actor:give_info_portion ("teleport_part_indtalled")
		news_manager.send_tip(db.actor, "teleport_part_indtalled_tip1", nil, "anomal", 3000, nil)
elseif ( db.actor:dont_has_info("teleport_part_indtalled") and xr_conditions.actor_wears_headhunter_outfit() ~= true ) then
		addon.actor_disable_inventory()
		news_manager.send_tip(db.actor, "teleport_part_indtalled_tip3", nil, "anomal", 3000, nil)
		amk.spawn_item_in_inv("t_akumulator1")
elseif has_alife_info("teleport_part_indtalled") then
		addon.actor_disable_inventory()
		news_manager.send_tip(db.actor, "teleport_part_indtalled_tip2", nil, "anomal", 3000, nil)
		amk.spawn_item_in_inv("t_akumulator1")
end
end

t['t_akumulator2'] = function()
if ( xr_conditions.actor_wears_headhunter_outfit() ~= true or xr_conditions.actor_wears_headhunter_m1outfit() ~= true ) then
	addon.teleport_to_t_part()
	addon.actor_disable_inventory()
	soundtrack.lift_up()
elseif xr_conditions.actor_wears_headhunter_outfit() ~= true then
	addon.actor_disable_inventory()
	news_manager.send_tip(db.actor, "teleport_part_indtalled_tip3", nil, "anomal", 3000, nil)
	amk.spawn_item_in_inv("t_akumulator2")
end
end

t['x18_subj_documents'] = function()
	db.actor:give_info_portion ("x18_subjects_info")
	addon.actor_disable_inventory()
	soundtrack.shelest()
end

t['fotocamera'] = function()
-- if xr_conditions.actor_in_zone(nil,nil,{"garb_heap_novice_death_zone"}) then
	local obj = level_object_by_sid(8469)
	if obj and obj ~= nil and has_alife_info("garb_hangar_anomaly_start") and db.actor:dont_has_info("garb_hangar_anomaly_foto") then
	db.actor:give_info_portion ("garb_hangar_anomaly_foto")
	soundtrack.foto_click()
	addon.actor_disable_inventory()
	end
-- elseif xr_conditions.actor_out_zone(nil,nil,{"garb_heap_novice_death_zone"}) then
	-- addon.actor_disable_inventory()
	-- soundtrack.foto_click()	
	-- end
end

t['esc_carcrash_pda'] = function()
	db.actor:give_info_portion ("esc_carcrash_pda_info")
	xr_effects.release_doll_secretzone3()
end

t['rad_mashroom'] = function()
local psy = db.actor.psy_health
db.actor.psy_health = psy + 0.3
end

t['teapot_full'] = function()
local text = "Бодрость"
	amk.spawn_item_in_inv("teapot")
	db.actor:give_info_portion ("tea_effect")
	-- amk.g_start_timer("tea",0,1,0)
	start_real_timer(900, "timer_actions.teapot_timer_action")
	db.actor.power = 1.0
	db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
end

t['rat_trap_full'] = function()
	amk.spawn_item_in_inv("mutant_rat_corp")
	amk.spawn_item_in_inv("rat_trap_empty")
	soundtrack.rattrap_click()
end

t['biboran'] = function()
	addon_devices.biboran_use1()
end

t['redrik_vakcine'] = function()
	db.actor:disable_info_portion("agrund_virus_konteyner_opened")
end

t['agrund_virus_konteyner'] = function()
	db.actor:give_info_portion ("agrund_virus_konteyner_opened")
	addon.actor_disable_inventory()
	addon_dialogs.agrund_virus_konteyner_opened_think()
	soundtrack.sick_2()
end


t['army_receiver'] = function()
local text = "Невозможно использовать здесь"
if db.actor:dont_has_info("army_drop_heli_go") then
	if xr_conditions.actor_in_zone(nil,nil,{"esc_army_drop_zone"}) then
			db.actor:give_info_portion ("army_drop_heli_go")
			soundtrack.army_receiver_use()
			addon.actor_disable_inventory()
			news_manager.send_tip(db.actor, "esc_help_heli_tip1", nil, "heli", 5000, nil)
	elseif xr_conditions.actor_out_zone(nil,nil,{"esc_army_drop_zone"}) then
		db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
		addon.actor_disable_inventory()
	elseif has_alife_info("army_drop_heli_go") then
		news_manager.send_tip(db.actor, "esc_help_heli_tip2", nil, "heli", 5000, nil)
		addon.actor_disable_inventory()
	end
end
end


t['af_zuda'] = function()
	if db.actor:dont_has_info("reketirs_zuda_ready_to_use") then
		amk.spawn_item_in_inv("af_zuda")
	elseif has_alife_info("reketirs_zuda_ready_to_use") then
		local pos = db.actor:position()
		local fx_particle1 = particles_object("explosions\\group_items\\expl_wall_wave")
		local fx_particle2 = particles_object("explosions\\group_items\\expl_10_sparks_03")
		local snd = xr_sound.get_safe_sound_object([[ambient\x16\x16_psy_hit]])
			db.actor:hide_weapon()
			start_real_timer(1, "xr_effects.restore_weapon")
			addon.zuda_effect()
			addon.actor_disable_inventory()
			fx_particle1:play_at_pos(pos)
			fx_particle2:play_at_pos(pos)
			snd:play_at_pos(db.actor, pos, 0, sound_object.s3d)
			level.add_pp_effector("blink.ppe", 2007, false)
			amk.spawn_item_in_inv("af_zuda_empty")
			level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
			-- amk.g_start_timer("zuda2",0,1,0)
			start_real_timer(1800, "timer_actions.zuda_timer_action2")
		if db.actor:dont_has_info("reketirs_zuda_work") then
			db.actor:give_info_portion ("reketirs_zuda_work")
		end
	end
end

t['af_licvidator'] = function()
local pos = db.actor:position()
local fx_particle1 = particles_object("explosions\\group_items\\expl_flash_alpha")
local fx_particle2 = particles_object("explosions\\group_items\\expl_03_wave")
local snd = xr_sound.get_safe_sound_object([[ambient\mon_explosion]])
local karma = starvation.get_karma()
	db.actor:hide_weapon()
	start_real_timer(1, "xr_effects.restore_weapon")
	addon.af_licvidator_use()
	addon.actor_disable_inventory()
	level.add_pp_effector("blink.ppe", 2007, false)
	amk.spawn_item_in_inv("af_licvidator_empty")
	fx_particle1:play_at_pos(pos)
	fx_particle2:play_at_pos(pos)
	snd:play_at_pos(db.actor, pos, 0, sound_object.s3d)
	-- starvation.set_karma(0.2)
	xr_effects.karma_down()
	-- amk.g_start_timer("licvid",0,1,0)
	start_real_timer(1800, "timer_actions.licvid_timer_action2")
end


t['dynamite_pack'] = function()
local pos = db.actor:position()
local obj = level_object_by_sid( 8402 )
local level_name = level.name()
local news_text1 = "Динамит заложен"
local news_text2 = "Невозможно использовать здесь"

if level_name == "l03_agroprom" then
	if obj ~= nil and obj:position():distance_to_sqr(db.actor:position()) <= 2*2 then
	addon_dialogs.spawn_script_dynamite()
	db.actor:give_game_news(news_text1, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	addon.actor_disable_inventory()

	elseif obj ~= nil and obj:position():distance_to_sqr(pos) > 2*2 then
	db.actor:give_game_news(news_text2, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	alife():create('dynamite_pack', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	addon.actor_disable_inventory()
	end
elseif level_name ~= "l03_agroprom" then
	alife():create('dynamite_pack', db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	db.actor:give_game_news(news_text2, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
end
end



t['esc_btr_planshet'] = function()
	db.actor:give_info_portion ("wonder_task_done4")
	addon.actor_disable_inventory()
	xr_effects.give_dolltip2()
	soundtrack.wonderdoll_sucess_tip18()
	se_respawn.spawn("agr_camerer_box_guardian_respawn")
end

t['deadzone_dezintegrator'] = function()
	addon_dialogs.spawn_dezintegrator()
	addon.actor_disable_inventory()
end


t['dar_farm_seif_key'] = function()
local news_text1 = "Получен предмет: прибор ДАН-15"
local news_text2 = "Нечего открывать"
	if ( db.actor:object("farm_renegades_box") ~= nil and db.actor:dont_has_info("dar_farm_box_opened") ) then
		amk.remove_item(db.actor:object("farm_renegades_box"))
		amk.remove_item(db.actor:object("dar_farm_seif_key"))
		amk.spawn_item_in_inv("deadzone_dezintegrator")
		soundtrack.open_box()
		db.actor:give_game_news(news_text1, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
		db.actor:give_info_portion ("dar_farm_box_opened")
	elseif db.actor:object("farm_renegades_box") == nil then
		db.actor:give_game_news(news_text2, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	end
end

t['dar_fadric_rezak'] = function()
local text = "Невозможно использовать здесь"
	if xr_conditions.actor_in_zone(nil,nil,{"dar_podval_door_zone"}) and ( db.actor:object("dar_fadric_ballon1") ~= nil and db.actor:object("dar_fadric_ballon2") ~= nil ) then
	amk.remove_item(db.actor:object("dar_fadric_rezak"))
	amk.remove_item(db.actor:object("dar_fadric_ballon1"))
	amk.remove_item(db.actor:object("dar_fadric_ballon2"))
	db.actor:give_info_portion ("dar_fabric_door_to_x18_unblocked")
	addon.actor_disable_inventory()
	level.disable_input()
	-- amk.start_timer("rezak1",5)
	start_real_timer(5, "timer_actions.rezak_timer_action")
	soundtrack.svarka_work()
	level.add_pp_effector("agr_u_fade.ppe", 2007, false)

	elseif xr_conditions.actor_out_zone(nil,nil,{"dar_podval_door_zone"}) then
	db.actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	end
end

t['diesel_tank'] = function()
local news_text1 = "Горючая смесь изготовлена"
local news_text2 = "Нужен бензин"
	if db.actor:object("mobile_tank_full") ~= nil then
		amk.remove_item(db.actor:object("diesel_tank"))
		amk.remove_item(db.actor:object("mobile_tank_full"))
		amk.spawn_ammo_in_inv("ammo_flame", 15)
		-- amk.spawn_ammo_in_inv("ammo_flame2", 15)
		amk.spawn_item_in_inv("mobile_tank_empty")
		amk.spawn_item_in_inv("mobile_tank_empty")
		soundtrack.water_flow()
		db.actor:give_game_news(news_text1, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	elseif db.actor:object("mobile_tank_full") == nil then
		db.actor:give_game_news(news_text2, "ui\\ui_iconsTotal", Frect():set(83,470,83,47), 1000, 5000)
	end
end

t['harmonica_unic'] = function()
	addon.actor_disable_inventory()
	soundtrack.harmonica_unic_sing()
	start_real_timer(18, "timer_actions.harmon_timer_action")
	db.actor:hide_weapon()
	if xr_conditions.actor_in_zone(nil,nil,{"dar_fabric_zone"}) then
		db.actor:give_info_portion ("varg_harmonica_play")
	end
end

t['wonder_doll'] = function()
	if db.actor:dont_has_info("wonderdoll_task1") then
		addon_devices.wonder_doll_use_first_time()
	elseif has_alife_info("wonderdoll_task1") then
		addon_devices.wonder_doll_use_regular1()
		soundtrack.wonder_doll_talk()
	end	
end

t['esc_cheramic_box'] = function()
local pos = db.actor:position()
local fx_particle = "anomaly2\\studen_blowout"
	fx_particle = particles_object(fx_particle)
	fx_particle:play_at_pos(pos)
	soundtrack.acid_atack()
	db.actor.health = - 10
end


t['tutorial_sng_scopes'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_sng_scopes")  then
		db.actor:give_info_portion ("tutor_sng_scopes")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_sng_scopes") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end

t['tutorial_nato_scopes'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_nato_scopes")  then
		db.actor:give_info_portion ("tutor_nato_scopes")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_nato_scopes") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end

t['tutorial_sng_sil'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_sng_sil")  then
		db.actor:give_info_portion ("tutor_sng_sil")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_sng_sil") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end

t['tutorial_nato_sil'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_nato_sil")  then
		db.actor:give_info_portion ("tutor_nato_sil")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_nato_sil") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end

t['tutorial_sng_grenl'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_sng_grenl")  then
		db.actor:give_info_portion ("tutor_sng_grenl")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_sng_grenl") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end

t['tutorial_nato_grenl'] = function()
	soundtrack.shelest()
	if db.actor:dont_has_info("tutor_nato_grenl")  then
		db.actor:give_info_portion ("tutor_nato_grenl")
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action1")
	elseif has_alife_info("tutor_nato_grenl") then
		start_real_timer(2, "timer_actions.tutor_book_read_timer_action2")
	end
end


t['saper_shovel'] = function()
	addon.shovel_use()
end

t['anomal_map_garbage'] = function()
	addon_devices.anomal_map_garbage_use()
	soundtrack.shelest()
end

t['turret_box'] = function()
	soundtrack.pkm_activate()
	level.disable_input()
	addon.actor_disable_inventory()
	addon_devices.use_turret_interface_installing()
	start_real_timer(5, "timer_actions.turret1timer_action")
end

t['powder'] = function()
	addon.powder_used()
end
t['equipment_bag'] = function()
	addon.equipment_bag_use()
end
t['medic_bag'] = function()
	addon.medic_pack_use()
end
t['gidroperit'] = function()
	addon.gidroperit_used()
end
t['afscanner'] = function()
	addon_dialogs.actor_disable_inventory()
	start_real_timer(1, "addon_devices.afscanner_start")
	db.actor:hide_weapon()
	if db.actor:dont_has_info("first_afscanner_using") then
		db.actor:give_info_portion ("first_afscanner_using")
	end
end



t['flyaga_full'] = function()
local pow = db.actor.power
	amk.spawn_item_in_inv("flyaga_empty")
	db.actor.power = pow + 0.3
end

t['flyaga_bad'] = function()
	amk.spawn_item_in_inv("flyaga_empty")
	db.actor.power = 1.0
	addon.sickness()
end

t['flyaga_empty'] = function()
	addon.use_flyaga_empty()
end



t['unic_flyaga_full'] = function()
	amk.spawn_item_in_inv("unic_flyaga_empty")
	db.actor.power = 1.0
end

t['unic_flyaga_empty'] = function()
	addon.use_unic_flyaga_empty()
end



t['boarleg_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['flesheye_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['pseudotail_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['krovosos_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['tushkano_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['pseudogig_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['conserva_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end
t['salo_soup'] = function()
	amk.spawn_item_in_inv("bowler")
end

t['matches'] = function()
	addon.matches_use()
	soundtrack.matches()
end
t['lighter'] = function()
if db.actor:dont_has_info("arts_powerup_fire") then
	addon.lighter_use()
	soundtrack.lighter()
elseif has_alife_info("arts_powerup_fire") then
	addon_devices.matches_use()
end
end

t['skrepka'] = function()
if xr_conditions.actor_in_zone(nil,nil,{"kazarma_door_zone"}) and db.actor:dont_has_info("kazarma_door_broken") and db.actor:dont_has_info("kazarma_door_open") then
		db.actor:give_info_portion ("kazarma_door_broken")
		db.actor:give_info_portion ("kazarma_door_open")
		soundtrack.door_broken()
elseif xr_conditions.actor_in_zone(nil,nil,{"x18freezer_door_zone"}) and has_alife_info("subj5_freezer_info") then
		db.actor:give_info_portion ("x18freezer_door_open")
		soundtrack.door_broken()
	end
	if xr_conditions.actor_out_zone(nil,nil,{"kazarma_door_zone"}) then
		news_manager.send_tip(db.actor, "kazarma_door_too_far", nil)
	end
end

t['ibuprophen'] = function()
	if db.actor:dont_has_info("ibuprophen_used")  then
	db.actor:give_info_portion ("ibuprophen_used")
	end
	db.actor:disable_info_portion("pain")
	soundtrack.ibuprophen_used()
	if timer_exists("pain_timer") then
		get_timer("pain_timer"):remove()
	end
end

t['flare_1'] = function()
	addon.flare1_use()
end
t['flare_2'] = function()
	addon.flare2_use()
end

t['knife_1'] = function()
	addon.knife1_use()
end
t['knife_2'] = function()
	addon.knife2_use()
end
t['knife_3'] = function()
	addon.knife3_use()
end
t['knife_4'] = function()
	addon.knife4_use()
end
t['knife_5'] = function()
	addon.knife5_use()
end
t['knife_6'] = function()
	addon.knife6_use()
end
t['montirovka'] = function()
	addon.montirovka_use()
	soundtrack.montirovka_use()
end

t['vint'] = function()
local murder = starvation.get_murder()
local addiction = starvation.get_addiction()
	if addiction >= 0.6 then
		start_real_timer(1000, "timer_actions.narko_timer_action")
		db.actor:give_info_portion("narko_addiction")
	elseif addiction < 0.6 then
		starvation.add_addiction(0.2)
	end
	db.actor:disable_info_portion("bonebreak")
	db.actor:disable_info_portion("pain")
	if murder>0.02 then starvation.set_murder(0) end	--	зануляем совесть, чтобы можно было спокойно спать;
end


t['binocl_army'] = function()
	addon.binocl1_use()
end

t['binocl_civil'] = function()
	addon.binocl2_use()
end


t['mobile_changer_33'] = function()
	local obj = alife():create('m_ruck2', db.actor:position(), db.actor:level_vertex_id(),db.actor:game_vertex_id())
	amk.add_spot_on_map(obj.id, "red_location", "Хабар Жекана")
	xr_effects.habar_pickup_think()
	addon.actor_disable_inventory()
	soundtrack.habar_use()
end


t['mikstura'] = function()
local karma = starvation.get_karma()
	if karma>=0.3 then
		db.actor:give_info_portion("miksture_drink")
		-- amk.g_start_timer("mikst",0,4,0)
		start_real_timer(1000, "timer_actions.miksture_timer_action")
		db.actor:disable_info_portion("sickness")
	elseif karma<0.3 then
		addon.actor_disable_inventory()
		addon.mixture_bad_work()
	end
end

t['anabiotik'] = function()
		--news_manager.send_tip(db.actor, "anabiotik", nil)
		sleep_manager.sleep_one_hour()
		db.actor:disable_info_portion("surge_process_stage_01")
		db.actor:disable_info_portion("surge_process_stage_02")
		db.actor:disable_info_portion("surge_process_stage_03")
		db.actor:disable_info_portion("surge_process_stage_04")
		db.actor:disable_info_portion("surge_process_stage_05")
		db.actor:disable_info_portion("surge_process_stage_06")
		db.actor:disable_info_portion("surge_process_stage_07")
		db.actor:disable_info_portion("surge_process_stage_08")
		db.actor:disable_info_portion("surge_process_stage_09")
		db.actor:disable_info_portion("surge_process_stage_10")
		db.actor:disable_info_portion("surge_process_stage_11")
		db.actor:disable_info_portion("surge_process_stage_12")
		db.actor:disable_info_portion("surge_process_stage_13")
		db.actor:disable_info_portion("surge_process_stage_14")
		level.remove_cam_effector(1974)
		level.remove_pp_effector(1003)
		level.remove_cam_effector(2004)
		level.remove_pp_effector(299)
		xr_sound.set_actor_sound("")
		ogsm_surge.surge_reset()
end
t['armor_remkit'] = function()
	addon.armor_remkit_use()
end
t['weapon_remkit'] = function()
	addon_devices.weapon_remkit_use()
end
t['hand_radio_f'] = function()
	ui_handradio.open_radio_dialog()
end

