class "WeatherManager"
function WeatherManager:__init()
	--printf					("WeatherManager:WeatherManager()")
	self.weather_change_day = 0
	self.update_time = 0
	self.update_level = ""
end

function WeatherManager:reset()
	self:reset_2()
    
    
	self:select_weather(true)
end

function WeatherManager:reset_2()
	--printf					("WeatherManager:WeatherManager():Reset()")
	-- Загрузить кондлист с погодой.
	local ini = ini_file("game.ltx")
	local weather = utils.cfg_get_string(ini, level.name(), "weathers", db.actor, false, "", "default")
	local postprocess = utils.cfg_get_string(ini, level.name(), "postprocess", db.actor, false, "")
	if postprocess ~= nil then
		printf("LEVEL POSTPROCESS: level: [%s], postprocess: [%s]", level.name(), postprocess)
		level.add_pp_effector(postprocess, 999, true)	
	else
		printf("LEVEL POSTPROCESS: level: [%s], postprocess: [none]", level.name())
		level.remove_pp_effector(999)
	end	

    --in xr_logic.parse_condlist(db.actor, level.name(), "weather", "clear") only the last parameter does anything, first should be kept as actor, the other two are irrelevant as far as I can tell 
    --Mawrak
    
    --third day is the starting day
    
    if device():is_r2_active() then
        if level.name() == "l01_escape" then
            local day = level.get_time_days()
            local day_check = getWeatherDay(day)
            
            if day_check == 1 then
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "cloudy_light_rain")
            elseif day_check == 2 then
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "cloudy_light")
            else
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "vivid")
            end
            
        else
            self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", weather)
        end
    else
        if level.name() == "l01_escape" then
            local day = level.get_time_days()
            local day_check = getWeatherDay(day)
            
            if day_check == 1 then
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "remake")
            elseif day_check == 2 then
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "clear_alt")
            else
                self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", "clear")
            end
            
        else
            self.weather_list = xr_logic.parse_condlist(db.actor, level.name(), "weather", weather)
        end
    end
    
    

    
end


function WeatherManager:select_weather(now)
	self.weather_change_day = level.get_time_days()
	self.update_level = level.name()
    self:reset_2()
	local weather = xr_logic.pick_section_from_condlist(db.actor, db.actor, self.weather_list)
	printf("WEATHER: '%s' now '%s'", weather, tostring(now))
	level.set_weather(weather,now);
end

function WeatherManager:load(F)
	self.update_level 		= F:r_stringZ();
	self.update_time 		= F:r_u32();
end

function WeatherManager:save(F)
	F:w_stringZ				(self.update_level);
	F:w_u32					(self.update_time);
end


local torch_on = false


function WeatherManager:update()
	if self.update_time <= time_global() then
		printf("weather_update day [%s]", level.get_time_days())
		
		if self.update_level ~= level.name() then
			self:select_weather(true)			
		end
		
		
		self.update_time = self.update_time + 10000
	end
    if self.weather_change_day ~= level.get_time_days() then
		self:select_weather(true)
	end
    
    if rain_fix == nil then
		self:select_weather(true)
        rain_fix = 1
	end
    
    --Other Update
    if db.actor then
    
    --Food - Hunger and Thirst
    
    if db.actor:item_in_slot(7) and db.actor:item_in_slot(8) then
            starvation.starvation_update()
        end
         
    end
    
    if db.actor:item_in_slot(9) then
    
        if torch then
            local torch2 = db.actor:item_in_slot(9)
            if torch:id() ~= torch2:id() then
                torch_con = nil
                torch_on = false
                torch = db.actor:item_in_slot(9)
            end
        else
            torch = db.actor:item_in_slot(9)
        end
    
    
        
        
        
        
        if torch_con==nil then
            torch_con = torch:condition()
        else
            if torch_con == torch:condition() and torch_on == true then
            
                local snd = sound_object("torch_click")
                snd:play_no_feedback(db.actor, sound_object.s2d, 0, vector():set(0, 0, 0), 1);
                
                torch_on = false
                --torch_con = torch:condition()
                
            elseif torch_con ~= torch:condition() and torch_on == false then
            
                local snd = sound_object("torch_click")
                snd:play_no_feedback(db.actor, sound_object.s2d, 0, vector():set(0, 0, 0), 1);
                
                torch_on = true
                --torch_con = torch:condition()
            end
        end
        torch_con = torch:condition()

    else
        torch = nil
        torch_con = nil
        torch_on = false
    end

    
end

function getWeatherDay(day)
    local remainder = (day - 1) % 3
    if remainder == 0 then
        return 1
    elseif remainder == 1 then
        return 2
    else
        return 3
    end
end