--	Схема озвучки
nstl = 64

snd_ini = ini_file("misc\\script_sound.ltx")

theme = {}
ph_snd_themes = {}





ph_snd_themes["hunter2_hello"] = {[[characters_voice\\scenario\\hunter2_hello]]}
ph_snd_themes["hunter1_to_tirsa"] = {[[characters_voice\\scenario\\hunter1_to_tirsa]]}

ph_snd_themes["abdul_pray"] = { "characters_voice\\scenario\\abdul_pray_1",
	                        "characters_voice\\scenario\\abdul_pray_2",
		"characters_voice\\scenario\\abdul_pray_3",
		"characters_voice\\scenario\\abdul_pray_4",
		"characters_voice\\scenario\\abdul_pray_5" }
ph_snd_themes["post_oficer2_talk"] = {[[characters_voice\\scenario\\post_oficer2_talk]]}
ph_snd_themes["kolbasa_i_batony"] = {[[characters_voice\\scenario\\post_soldier10_toilet_talk_1]],
					[[characters_voice\\scenario\\post_soldier10_toilet_talk_2]]}
ph_snd_themes["rupor_idle"] = { "characters_voice\\scenario\\escape\\megafon_1",
	                        "characters_voice\\scenario\\escape\\megafon_2",
		"characters_voice\\scenario\\escape\\megafon_3",
		"characters_voice\\scenario\\escape\\megafon_4"}
ph_snd_themes["rupor_alarm"] = { "characters_voice\\scenario\\megafon\\megafon_alarm_1",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_2",
		"characters_voice\\scenario\\megafon\\megafon_alarm_3",
		"characters_voice\\scenario\\megafon\\megafon_alarm_4",
		"characters_voice\\scenario\\megafon\\megafon_alarm_5",
		"characters_voice\\scenario\\megafon\\megafon_alarm_6",
		"characters_voice\\scenario\\megafon\\megafon_alarm_7",
		"characters_voice\\scenario\\megafon\\megafon_alarm_8",
		"characters_voice\\scenario\\megafon\\megafon_alarm_9",
		"characters_voice\\scenario\\megafon\\megafon_alarm_10",
		"characters_voice\\scenario\\megafon\\megafon_alarm_11",
		"characters_voice\\scenario\\megafon\\megafon_alarm_12",
		"characters_voice\\scenario\\megafon\\megafon_alarm_13"}
ph_snd_themes["rupor_sirena"] = {[[characters_voice\scenario\siren1]]}							
ph_snd_themes["volk_help"] = { "characters_voice\\scenario\\volk_help_1",
	                        "characters_voice\\scenario\\volk_help_2",
		"characters_voice\\scenario\\volk_help_3" }		
					
ph_snd_themes["skidan_hello1"]	= { "characters_voice\\scenario\\skidan_hello1_1",
	                        "characters_voice\\scenario\\skidan_hello1_2",
							"characters_voice\\scenario\\skidan_hello1_3",
							"characters_voice\\scenario\\skidan_hello1_4" }	
ph_snd_themes["skidan_hello2"]	= { "characters_voice\\scenario\\skidan_hello2_1",
	                        "characters_voice\\scenario\\skidan_hello2_2" }								
									
ph_snd_themes["skidan_radio_music"] = { "characters_voice\\scenario\\new_music\\skidan_music_2",
		"characters_voice\\scenario\\new_music\\skidan_music_3",
		"characters_voice\\scenario\\new_music\\skidan_music_4" }
ph_snd_themes["agr_nii_rupor_music"] = { "characters_voice\\scenario\\new_music\\agr_nii_rupor_music_1",
		"characters_voice\\scenario\\new_music\\agr_nii_rupor_music_2",
		"characters_voice\\scenario\\new_music\\agr_nii_rupor_music_3",
		"characters_voice\\scenario\\new_music\\agr_nii_rupor_music_4" }
ph_snd_themes["quit"] = {[[characters_voice\\scenario\\no_sound]]}
ph_snd_themes["vetryak_work"] = {[[ambient\\x16\\x16_engine2_run]]}

ph_snd_themes["atp_matugalnik_idle"] = {[[characters_voice\scenario\jekan\esc_atp_rupor_music]]}

ph_snd_themes["post_soldier10_arest_call"] = {[[characters_voice\\scenario\\post_soldier10_arest_call_1]],
					[[characters_voice\\scenario\\post_soldier10_arest_call_2]]}

ph_snd_themes["bomzh_hello"] = {[[characters_voice\\scenario\\vanomas_hello]]}

ph_snd_themes["dont_shoot"] = { "characters_voice\\scenario\\dont_shoot_1",
	                        "characters_voice\\scenario\\dont_shoot_2",
		"characters_voice\\scenario\\dont_shoot_3",
		"characters_voice\\scenario\\dont_shoot_4" }
ph_snd_themes["esc_radiostation"] = { "characters_voice\\scenario\\esc_radiostation_1",
		"characters_voice\\scenario\\esc_radiostation_2",
		"characters_voice\\scenario\\esc_radiostation_3",
		"characters_voice\\scenario\\esc_radiostation_4" }
ph_snd_themes["dar_vagon_radio_music"] = { "characters_voice\\scenario\\dar_vagon_radio_music_1",
	                        "characters_voice\\scenario\\dar_vagon_radio_music_2"}
ph_snd_themes["x18_entrance_vmordu"] = {[[characters_voice\\scenario\\x18_entrance_vmordu]]}
ph_snd_themes["dar_suicider_woman_cry1"] = {[[characters_voice\\scenario\\dar_suicider_woman_cry1]]}
ph_snd_themes["dar_suicider_woman_cry2"] = {[[characters_voice\\scenario\\dar_suicider_woman_cry2]]}

ph_snd_themes["dezintegrator_work1"] = {[[characters_voice\\scenario\\dezintegrator_work1]]}
ph_snd_themes["dar_izlom_werwolf_talk1"] = {[[characters_voice\\scenario\\dar_izlom_werwolf_talk1]]}
ph_snd_themes["dar_izlom_werwolf_talk2"] = {[[characters_voice\\scenario\\dar_izlom_werwolf_talk2]]}
ph_snd_themes["diesel_generator_work"]	= { [[car\car_traktor]],
						[[car\car_traktor]],
						[[car\car_traktor]] }
ph_snd_themes["dog_bark"]	= { [[monsters\dog\bdog_idle_1]],
						[[monsters\dog\bdog_idle_2]],
						[[monsters\dog\bdog_idle_3]] }

ph_snd_themes["ventilyator_work"] = {[[characters_voice\\scenario\\ventilyator_work]]}
ph_snd_themes["subject_psy_atack"] = {[[characters_voice\\scenario\\subject_psy_atack]]}
ph_snd_themes["x18_matugalnik_idle"] = {[[characters_voice\scenario\new_music\x18_matugalnik_idle_1]]}
ph_snd_themes["mushroom_colony_bul_bul"] = {[[characters_voice\scenario\mushroom_colony_bul_bul]]}
ph_snd_themes["x18_matugalnik_pray"] = {[[characters_voice\scenario\x18_matugalnik_1]]}
ph_snd_themes["x18_matugalnik_alarm"] = {[[characters_voice\scenario\x18_matugalnik_2]]}
ph_snd_themes["x18_incubator_work"] = {[[characters_voice\scenario\x18_incubator_work]]}
ph_snd_themes["x18_incubator_alarm"] = {[[characters_voice\scenario\x18_incubator_alarm]]}
ph_snd_themes["anomal_radio_music1"] = {[[characters_voice\scenario\radio_sound]]}
ph_snd_themes["anomal_radio_music2"] = {[[characters_voice\scenario\radio_voice]]}
ph_snd_themes["silence"] = {[[characters_voice\scenario\silence]]}
ph_snd_themes["bar_magnitofon_music"] = {[[characters_voice\scenario\bar_magnitofon_music]]}

ph_snd_themes["script_magnitofon_music1"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound3",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound5",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound13",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound17"}
ph_snd_themes["script_magnitofon_music2"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound6",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound7",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound8"}
ph_snd_themes["script_magnitofon_music3"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound1",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound9",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound10",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound11"}
ph_snd_themes["script_magnitofon_music4"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound15",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound19",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound20",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound4"}
ph_snd_themes["script_magnitofon_music5"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound18",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound12",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound14"}
ph_snd_themes["script_magnitofon_music6"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound21",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound22",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound23",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound24"}
ph_snd_themes["script_magnitofon_music7"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound25",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound26",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound27",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound28"}
ph_snd_themes["script_magnitofon_music8"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound29",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound30",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound31",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound32"}
ph_snd_themes["script_magnitofon_music9"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound33",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound34",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound35",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound36"}
ph_snd_themes["script_magnitofon_music10"]	= {"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound37",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound38",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound39",
				"characters_voice\\scenario\\jekan\\jekan_secret_radio_sound40"}
ph_snd_themes["script_doll_music"] = {[[characters_voice\scenario\jekan\jekan_secret_radio_sound40]]}
ph_snd_themes["bar_ventilyators_sound"] = {[[ambient\transformer_hum1]]}
ph_snd_themes["drunk"] = { "characters_voice\\scenario\\drunk_1",
	                        "characters_voice\\scenario\\drunk_2",
		"characters_voice\\scenario\\drunk_3",
		"characters_voice\\scenario\\drunk_4",
		"characters_voice\\scenario\\drunk_5",
		"characters_voice\\scenario\\drunk_6",
		"characters_voice\\scenario\\drunk_7",
		"characters_voice\\scenario\\drunk_8" }
ph_snd_themes["ros_master_soundzone"] = { "soundtrack\\controller\\24",
	                        "soundtrack\\controller\\25",
		"soundtrack\\controller\\17",
		"soundtrack\\controller\\14",
		"soundtrack\\controller\\6",
		"soundtrack\\horror_time\\1",
		"soundtrack\\horror_time\\2",
		"soundtrack\\horror_time\\10",
		"soundtrack\\horror_time\\14",
		"soundtrack\\horror_time\\17",
		"soundtrack\\horror_time\\22",
		"soundtrack\\horror_time\\23",
		"soundtrack\\horror_time\\24",
		"soundtrack\\horror_time\\25",
		"soundtrack\\horror_time\\31"}
ph_snd_themes["ros_house_radiola_music"] = { "script_replics\\megafon\\music\\megafon_music_15",
		"script_replics\\megafon\\music\\megafon_music_14",
		"script_replics\\megafon\\music\\megafon_music_13",
		"script_replics\\megafon\\music\\megafon_music_12",
		"script_replics\\megafon\\music\\megafon_music_11",
		"script_replics\\megafon\\music\\megafon_music_9",
		"script_replics\\megafon\\music\\megafon_music_6" }
ph_snd_themes["predb_bariga_radio_music"] = { "characters_voice\\scenario\\new_music\\predb_bariga_radio_snd3",
		"characters_voice\\scenario\\new_music\\predb_bariga_radio_snd2",
		"characters_voice\\scenario\\new_music\\predb_bariga_radio_snd3" }
ph_snd_themes["predb_firestation_rupor_music"] = { "characters_voice\\scenario\\new_music\\predb_firestation_rupor_music1",
		"characters_voice\\scenario\\new_music\\predb_firestation_rupor_music2",
		"characters_voice\\scenario\\new_music\\predb_firestation_rupor_music3" }
ph_snd_themes["moisha_hello"]	= { "characters_voice\\scenario\\moisha_hello_1",
	                        "characters_voice\\scenario\\moisha_hello_2" }				
ph_snd_themes["deadmask_scary_sound"] = { "soundtrack\\dog_phantom\\10",
		"soundtrack\\controller\\1",
		"soundtrack\\controller\\2",
		"soundtrack\\controller\\3",
		"soundtrack\\controller\\4",
		"soundtrack\\controller\\5",
		"soundtrack\\controller\\6",
		"soundtrack\\controller\\8",
		"soundtrack\\controller\\11",
		"soundtrack\\controller\\12",
		"soundtrack\\controller\\13",
		"soundtrack\\controller\\19",
		"soundtrack\\controller\\25",
		"soundtrack\\dog_phantom\\1",
		"soundtrack\\dog_phantom\\2",
		"soundtrack\\dog_phantom\\5",
		"soundtrack\\dog_phantom\\7",
		"soundtrack\\dog_phantom\\3" }
ph_snd_themes["yan_comander_burer_see"] = {[[characters_voice\\scenario\\yan_comander_burer_see]]}
ph_snd_themes["yan_sold_comander_alarm"] = {[[characters_voice\\scenario\\yan_sold_comander_alarm]]}
ph_snd_themes["yan_sold_base_raciya_music"] = { "script_replics\\radio\\message\\radio_voice_1",
		"script_replics\\radio\\message\\radio_voice_2",
		"script_replics\\radio\\message\\radio_voice_3" }
ph_snd_themes["yan_lost_camp_scaner_snd"] = {[[detectors\contact_8]]}
ph_snd_themes["ros_rescuers_vmordu"] = {[[characters_voice\\scenario\\ros_rescuers_vmordu]]}

ph_snd_themes["mil_village_dedok_radio_music"] = { "characters_voice\\scenario\\new_music\\mil_village_dedok_radio_music_1",
		"characters_voice\\scenario\\new_music\\mil_village_dedok_radio_music_2",
		"characters_voice\\scenario\\new_music\\mil_village_dedok_radio_music_3" }

ph_snd_themes["mil_freak_panik1"] = {[[characters_voice\\scenario\\mil_freak_panik1]]}	
ph_snd_themes["mil_kazarma2mafon"] = {[[characters_voice\scenario\mil_kazarma2_mafon_snd]]}
ph_snd_themes["rad_secret_talk_music"] = {[[characters_voice\scenario\new_music\rad_secret_talk_music]]}
ph_snd_themes["rad_abdul_actor_check"] = { "characters_voice\\scenario\\rad_abdul_actor_check_1",
		"characters_voice\\scenario\\rad_abdul_actor_check_2",
		"characters_voice\\scenario\\rad_abdul_actor_check_3" }
ph_snd_themes["rad_trader_radio_music"] = { "characters_voice\\scenario\\jekan\\rad_trader_radio_music_1",
		"characters_voice\\scenario\\jekan\\rad_trader_radio_music_2"}
ph_snd_themes["rad_trader_radio_music2"] = {[[characters_voice\scenario\jekan\rad_trader_radio2]]}
ph_snd_themes["pri_detsad_radio_music"] = {[[characters_voice\scenario\jekan\pri_detsad_radio_music]]}
ph_snd_themes["pri_detsad_cry"] = { "characters_voice\\scenario\\jekan\\pri_detsad_cry_1",
		"characters_voice\\scenario\\jekan\\pri_detsad_cry_2",
		"characters_voice\\scenario\\jekan\\pri_detsad_cry_3",
		"characters_voice\\scenario\\jekan\\pri_detsad_cry_4" }
ph_snd_themes["pri_agent_lider_speech1"] = {[[characters_voice\\scenario\\pri_agent_lider_speech1]]}	
ph_snd_themes["pri_agent_lider_speech2"] = {[[characters_voice\\scenario\\pri_agent_lider_speech2]]}	
ph_snd_themes["pri_agent_lider_speech3"] = {[[characters_voice\\scenario\\pri_agent_lider_speech3]]}	
ph_snd_themes["pri_agent_lider_speech4"] = {[[characters_voice\\scenario\\pri_agent_lider_speech4]]}	
ph_snd_themes["pri_agent_lider_speech5"] = {[[characters_voice\\scenario\\pri_agent_lider_speech5]]}	
ph_snd_themes["goldsphere_overheat"] = {[[characters_voice\scenario\goldsphere_overheat]]}
ph_snd_themes["general_scientist_goodbye"] = {[[characters_voice\scenario\general_scientist_goodbye]]}		
ph_snd_themes["hermit_talk"] = { "characters_voice\\scenario\\hermit_talk_1",
		"characters_voice\\scenario\\hermit_talk_2",
		"characters_voice\\scenario\\hermit_talk_3",
		"characters_voice\\scenario\\hermit_talk_4",
		"characters_voice\\scenario\\hermit_talk_5",
		"characters_voice\\scenario\\jekan\\hermit_talk_6" }
ph_snd_themes["predb_well_sound"] = { "soundtrack\\horror_time\\1",
		"soundtrack\\horror_time\\3",
		"soundtrack\\horror_time\\5",
		"soundtrack\\horror_time\\30",
		"soundtrack\\horror_time\\32",
		"soundtrack\\horror_time\\33",
		"soundtrack\\horror_time\\36" }
ph_snd_themes["predb_village_trap_snd"] = { "characters_voice\\human_01\\stalker\\help\\wounded_heavy\\help_1",
		"characters_voice\\human_01\\stalker\\help\\wounded_heavy\\help_2",
		"characters_voice\\human_01\\stalker\\help\\wounded_heavy\\help_3",
		"characters_voice\\human_01\\stalker\\help\\wounded_heavy\\help_4",
		"characters_voice\\human_01\\stalker\\help\\wounded_heavy\\help_5" }	
ph_snd_themes["predb_village_music_box_snd"] = {[[characters_voice\scenario\jekan\predb_village_music_box]]}			
ph_snd_themes["fire_burns"] = {[[ambient\fire1]]}	
ph_snd_themes["predb_village_radio_snd"] = {[[characters_voice\scenario\jekan\predb_village_radio_snd]]}		
ph_snd_themes["pri_strange_snd1"] = {[[characters_voice\scenario\jekan\pri_strange_snd1]]}		
ph_snd_themes["pri_strange_snd2"] = { "characters_voice\\scenario\\jekan\\pri_strange_snd2_1",
		"characters_voice\\scenario\\jekan\\pri_strange_snd2_2",
		"characters_voice\\scenario\\jekan\\pri_strange_snd2_3",
		"characters_voice\\scenario\\jekan\\pri_strange_snd2_4",
		"characters_voice\\scenario\\jekan\\pri_strange_snd2_5" }
ph_snd_themes["pri_strange_snd3"] = { "characters_voice\\scenario\\jekan\\pri_strange_snd3_1",
		"characters_voice\\scenario\\jekan\\pri_strange_snd3_2",
		"characters_voice\\scenario\\jekan\\pri_strange_snd3_3",
		"characters_voice\\scenario\\jekan\\pri_strange_snd3_4",
		"characters_voice\\scenario\\jekan\\pri_strange_snd3_5" }
ph_snd_themes["predb_nature_snd1"] = { "characters_voice\\scenario\\jekan\\predb_nature_snd_1",
		"characters_voice\\scenario\\jekan\\predb_nature_snd_2",
		"characters_voice\\scenario\\jekan\\predb_nature_snd_3" }
ph_snd_themes["predb_nature_snd2"] = { "characters_voice\\scenario\\jekan\\predb_nature_snd_4",
		"characters_voice\\scenario\\jekan\\predb_nature_snd_5",
		"characters_voice\\scenario\\jekan\\predb_nature_snd_6" }		
ph_snd_themes["kontrab5_storytell1"] = {[[characters_voice\\scenario\\kontrab5_story_1]]}
ph_snd_themes["kontrab5_storytell2"] = {[[characters_voice\\scenario\\kontrab5_story_2]]}
ph_snd_themes["kontrab5_storytell3"] = {[[characters_voice\\scenario\\kontrab5_story_3]]}
ph_snd_themes["kontrab5_storytell4"] = {[[characters_voice\\scenario\\kontrab5_story_4]]}
ph_snd_themes["kontrab5_storytell5"] = {[[characters_voice\\scenario\\kontrab5_story_5]]}
ph_snd_themes["kontrab5_storytell6"] = {[[characters_voice\\scenario\\kontrab5_story_6]]}
ph_snd_themes["kontrab5_storytell7"] = {[[characters_voice\\scenario\\kontrab5_story_7]]}
ph_snd_themes["kontrab5_storytell8"] = {[[characters_voice\\scenario\\kontrab5_story_8]]}
ph_snd_themes["kontrab5_storytell9"] = {[[characters_voice\\scenario\\kontrab5_story_9]]}			
ph_snd_themes["predb_base_radio_snd"] = { "characters_voice\\scenario\\new_music\\predb_base_radio_snd_1",
		"characters_voice\\scenario\\new_music\\predb_base_radio_snd_2",
		"characters_voice\\scenario\\new_music\\predb_base_radio_snd_3" }		
ph_snd_themes["predb_firest_magnitofon_snd"] = {[[characters_voice\scenario\new_music\predb_firest_magnitofon_snd]]}			
ph_snd_themes["marouder_to_search"] = {[[characters_voice\human_01\bandit\fight\detour\detour_9]]}		
ph_snd_themes["predb_base_chimera_snd"] = { "monsters\\himera\\attack_0",
		"monsters\\himera\\attack_1",
		"monsters\\himera\\attack_2" }		
ph_snd_themes["predb_courier_guard_speech"] = {[[characters_voice\human_03\killer\fight\tolls\tolls_5]]}		
ph_snd_themes["catwoman_help"] = { "characters_voice\\scenario\\catwoman_help_1",
		"characters_voice\\scenario\\catwoman_help_2",
		"characters_voice\\scenario\\catwoman_help_3" }			
ph_snd_themes["catwoman_laught"] = {[[characters_voice\scenario\catwoman_laught]]}	
ph_snd_themes["predb_stoned_izlom_snd"] = { "characters_voice\\scenario\\predb_stoned_izlom_1",
		"characters_voice\\scenario\\predb_stoned_izlom_2",
		"characters_voice\\scenario\\predb_stoned_izlom_3",
		"characters_voice\\scenario\\predb_stoned_izlom_4",
		"characters_voice\\scenario\\predb_stoned_izlom_5" }		
ph_snd_themes["hunter_7_help"] = { "characters_voice\\scenario\\wounded_veteran_escape\\wounded_veteran_fight_1",
		"characters_voice\\scenario\\wounded_veteran_escape\\wounded_veteran_fight_2",
		"characters_voice\\scenario\\wounded_veteran_escape\\wounded_veteran_fight_3",
		"characters_voice\\scenario\\wounded_veteran_escape\\wounded_veteran_fight_4" }			
ph_snd_themes["mil_vsu_vmordu"] = {[[characters_voice\\scenario\\mil_vsu_vmordu]]}		
ph_snd_themes["flies"] = {[[anomaly\flies]]}
ph_snd_themes["zombied_idle"] = { "characters_voice\\human_01\\zombied\\states\\idle\\idle_1",
		"characters_voice\\human_01\\zombied\\states\\idle\\idle_2",
		"characters_voice\\human_01\\zombied\\states\\idle\\idle_3",
		"characters_voice\\human_01\\zombied\\states\\idle\\idle_4" }	

	
		




		
		
		
		
		






ph_snd_themes["freedom_speech_normal"]	= {"addon\\v_voskresnoy_shvatke",
                "script_replics\\megafon\\music\\megafon_music_10"}
ph_snd_themes["radio_music_bandit"] = {  "characters_voice\\scenario\\darkscape\\bandit_radio_1",
	                        "characters_voice\\scenario\\darkscape\\bandit_radio_2",
	                        "characters_voice\\scenario\\darkscape\\bandit_radio_3"
	                        }

ph_snd_themes["music"] = {  "characters_voice\\scenario\\megafon\\megafon_music_1",
	                        "characters_voice\\scenario\\megafon\\megafon_music_2",
	                        "characters_voice\\scenario\\megafon\\megafon_music_3"
	                        }

ph_snd_themes["koleso_pripyat_linhost"] = { "ogse\\cold_wind_11",
								"ambient\\squeak_metal1",
								"ambient\\squeak_metal2",
								"ambient\\iron_moaning1",
								"ambient\\howling_wind_u1",
								"ambient\\organic_moan1",
								"ogse\\rnd_outdoor\\rnd_darkwind5",
								"ogse\\cold_wind_11"
											}
														
ph_snd_themes["esc_music_horror_time"] = {"characters_voice\\scenario\\esc\\esc_music_horror_1",
										  "characters_voice\\scenario\\esc\\esc_music_horror_2",
										  "characters_voice\\scenario\\esc\\esc_music_horror_3",
										  "characters_voice\\scenario\\esc\\esc_music_blowout_1",
										  "characters_voice\\scenario\\esc\\esc_music_horror_4"
                                    }
ph_snd_themes["esc_music_day"] = {"characters_voice\\scenario\\esc\\esc_music_1",
								  "characters_voice\\scenario\\esc\\esc_music_3",
								  "characters_voice\\scenario\\esc\\esc_music_4",
								  "characters_voice\\scenario\\esc\\esc_music_5",
								  "characters_voice\\scenario\\esc\\esc_music_6",
								  "characters_voice\\scenario\\esc\\esc_music_2"
                                    }

ph_snd_themes["sidor_music_day"] = {"characters_voice\\scenario\\new_music\\skidan_music_1",
                                    "characters_voice\\scenario\\new_music\\skidan_music_2",
                                    "characters_voice\\scenario\\new_music\\skidan_music_3"}

ph_snd_themes["humor"] = {  "characters_voice\\scenario\\escape\\comandir_megafon_1",
							"characters_voice\\scenario\\escape\\comandir_megafon_2",
							"characters_voice\\scenario\\escape\\comandir_megafon_3",
							"characters_voice\\scenario\\escape\\comandir_megafon_4",
							"characters_voice\\scenario\\escape\\comandir_megafon_5",
							"characters_voice\\scenario\\escape\\comandir_megafon_6",
							"characters_voice\\scenario\\escape\\comandir_megafon_7",
							"characters_voice\\scenario\\escape\\comandir_megafon_8",
							"characters_voice\\scenario\\escape\\comandir_megafon_9",
							"characters_voice\\scenario\\escape\\comandir_megafon_10",
							"characters_voice\\scenario\\escape\\comandir_megafon_11",
							"characters_voice\\scenario\\escape\\comandir_megafon_12",
							"characters_voice\\scenario\\escape\\comandir_megafon_13",
							"characters_voice\\scenario\\escape\\comandir_megafon_14",
							"characters_voice\\scenario\\escape\\comandir_megafon_15",
							"characters_voice\\scenario\\escape\\comandir_megafon_16",
							"characters_voice\\scenario\\escape\\comandir_megafon_17"
	                        }	  
ph_snd_themes["epic"] = {   "characters_voice\\scenario\\escape\\megafon_1",
							"characters_voice\\scenario\\escape\\megafon_2",
							"characters_voice\\scenario\\escape\\megafon_3",
							"characters_voice\\scenario\\escape\\megafon_4",
							"characters_voice\\scenario\\escape\\megafon_5",
							"characters_voice\\scenario\\escape\\megafon_6",
							"characters_voice\\scenario\\escape\\megafon_7",
							"characters_voice\\scenario\\escape\\megafon_8",
							"characters_voice\\scenario\\escape\\megafon_9",
							"characters_voice\\scenario\\escape\\megafon_10",
							"characters_voice\\scenario\\escape\\megafon_11",
							"characters_voice\\scenario\\escape\\megafon_12"
	                        }                      
ph_snd_themes["alarm1"] = { "characters_voice\\scenario\\megafon\\megafon_alarm_1",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_10",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_11",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_12",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_13"
	                        }
ph_snd_themes["alarm2"] = { "characters_voice\\scenario\\megafon\\megafon_alarm_2",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_3",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_4",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_5",
	                        "characters_voice\\scenario\\megafon\\megafon_alarm_6"
	                      }
ph_snd_themes["siren"] =  { "ambient\\siren2" }

ph_snd_themes["bomb"] = {"detectors\\bomb_timer"}

ph_snd_themes["detector"] = {"detectors\\da-2_beep1"}

ph_snd_themes["radio_music"] = {"addon\\magnitofon_1",
                                    "addon\\radio_music_1",
                                    "addon\\radio_music_2",
                                    "addon\\radio_music_3",
                                    "addon\\radio_music_4"}
ph_snd_themes["dolg_speech"]	= {[[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
								   [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
								   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
								   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]],
								   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_3]],
								   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_4]],
								   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_5]],
[[addon\dolg_music_1]],
[[addon\dolg_music_2]]}

									   -- -------------------------------------------------------------ARENA_EXTENSION_MOD------------------------------------------------------------------
ph_snd_themes["arena_fight_10_sec"] = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_10_sec]]}
ph_snd_themes["arena_fight_20_sec"] = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_20_sec]]}
ph_snd_themes["arena_fight_30_sec"] = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_30_sec]]}
ph_snd_themes["arena_fight_40_sec"] = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_40_sec]]}
ph_snd_themes["arena_fight_50_sec"] = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_50_sec]]}

ph_snd_themes["aem_beast"] = {[[aem_snd\aem_beast]]}
ph_snd_themes["aem_bloodsucker"] = {[[aem_snd\aem_bloodsucker]]}
ph_snd_themes["aem_burer"] = {[[aem_snd\aem_burer]]}
ph_snd_themes["aem_fight_begin"] = {[[aem_snd\aem_fight_begin]]}
ph_snd_themes["aem_foul"] = {[[aem_snd\aem_foul]]}
ph_snd_themes["aem_no_chance"] = {[[aem_snd\aem_no_chance]]}
ph_snd_themes["aem_out_of_time"] = {[[aem_snd\aem_out_of_time]]}
ph_snd_themes["aem_pseudodog"] = {[[aem_snd\aem_pseudodog]]}
ph_snd_themes["aem_snork"] = {[[aem_snd\aem_snork]]}
ph_snd_themes["aem_special"] = {[[aem_snd\aem_special]]}
ph_snd_themes["aem_victory"] = {[[aem_snd\aem_victory]]}

ph_snd_themes["dolg_matugalnik"]	= {[[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
									   [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
									   [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
									   [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_3]],
									   [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_4]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_5]],
									   [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]]}

-- -------------------------------------------------------------ARENA_EXTENSION_MOD------------------------------------------------------------------


ph_snd_themes["dolg_alarm"]			= {[[characters_voice\scenario\bar\dolg_megafon\megaphone_duty_alarm]]}
ph_snd_themes["dolg_megafon_1_hit"] = {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_1]]}
ph_snd_themes["dolg_megafon_2_hit"] = {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_2]]}
ph_snd_themes["dolg_megafon_kill"]	= {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_3]]}
ph_snd_themes["arena_introduce_pseudodog"]	= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_pseudodog]]}
ph_snd_themes["arena_introduce_snork"]		= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_snork]]}
ph_snd_themes["arena_introduce_bloodsucker"]= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_bloodsucker]]}
ph_snd_themes["arena_introduce_burer"]		= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_burer]]}
ph_snd_themes["arena_introduce_savage"]		= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_zver]]}
ph_snd_themes["arena_actor_afraid"]			= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_coward]]}
ph_snd_themes["arena_fight_begin"]			= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_start]]}
ph_snd_themes["arena_fight_victory"]		= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_win_1]]}
ph_snd_themes["arena_fight_victory_notime"]	= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_win_2]]}
ph_snd_themes["arena_fight_lose"]			= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_out_of_time_win]]}
ph_snd_themes["arena_fight_death"]			= {[[characters_voice\scenario\bar\arena_megafon\mega_arena_dead]]}

ph_snd_themes["bar_start_megafon"]		= {[[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
									   [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
									   [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]]}

ph_snd_themes["mon_monolith_damaged"]			= {[[characters_voice\scenario\sarcofag\monolith_damaged]]}
ph_snd_themes["mon_monolith_heavy_damaged"]		= {[[characters_voice\scenario\sarcofag\monolith_heavy_damaged]]}
ph_snd_themes["mon_monolith_alarm"]				= {[[characters_voice\scenario\sarcofag\monolith_alarm]]}
ph_snd_themes["mon_monolith_recharged"]			= {[[characters_voice\scenario\sarcofag\monolith_recharged]]}

ph_snd_themes["sar_monolith_call"]			= {[[characters_voice\scenario\sarcofag\monolith_call_1]],
												[[characters_voice\scenario\sarcofag\monolith_call_2]],
												[[characters_voice\scenario\sarcofag\monolith_call_3]],
												[[characters_voice\scenario\sarcofag\monolith_call_4]],
												[[characters_voice\scenario\sarcofag\monolith_call_5]],
												[[characters_voice\scenario\sarcofag\monolith_call_6]],
												[[characters_voice\scenario\sarcofag\monolith_call_7]]}

ph_snd_themes["gar_seryi_shooting"]	= {[[characters_voice\scenario\garbage\distance_shooting]]}
ph_snd_themes["gar_seryi_shooting_2"]	= {[[characters_voice\scenario\bandits\bandit_replic_2]]}
-- ph_snd_themes["aes_battle1"] =        {"ambient\\battle_1"}
-- ph_snd_themes["aes_battle2"] =        {"ambient\\battle_2"}
ph_snd_themes["aes_battle1"] =        {"ambient\\silence"}
ph_snd_themes["aes_battle2"] =        {"ambient\\rt_ambient2"}
ph_snd_themes["gar_bandits_seryi"] =   {[[characters_voice\scenario\garbage\grey_bandit_1]],      
										[[characters_voice\scenario\garbage\grey_bandit_2]],
										[[characters_voice\scenario\garbage\grey_bandit_3]],
										[[characters_voice\scenario\garbage\grey_bandit_4]],
										[[characters_voice\scenario\garbage\grey_bandit_5]]}
ph_snd_themes["radar_drone"] = {"ambient\\radar_1"}
ph_snd_themes["radar_thunder"] = {"ambient\\radar_2"}
ph_snd_themes["radar_sparks"] = {"ambient\\radarsparks_1"}
ph_snd_themes["aes_teleport"] = {"anomaly\\teleport_incoming"}

ph_snd_themes["yan_antenna"] = {{"characters_voice\\scenario\\yantar\\psy_voices_1"}} --' Стерео

ph_snd_themes["radar_meh_on"] = {"ambient\\cooling_run"}
ph_snd_themes["radar_meh_off"] = {"ambient\\cooling_stop"}                               
ph_snd_themes["system_message_1"]	= {[[characters_voice\scenario\yantar\system_message_1]]}
ph_snd_themes["system_message_2"]	= {[[characters_voice\scenario\yantar\system_message_2]]}
ph_snd_themes["system_message_3"]	= {[[characters_voice\scenario\yantar\system_message_3]]}
ph_snd_themes["system_message_4"]	= {[[characters_voice\scenario\yantar\system_message_4]]}
ph_snd_themes["system_message_5"]	= {[[characters_voice\scenario\yantar\system_message_5]]}
ph_snd_themes["agro_test"]	= {[[weapons\grenade1]]}
ph_snd_themes["bar_arena_public"]	= {"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_2",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_3",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_4",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_5",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_6",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_7",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_8",
	                        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_9"
	                        }
ph_snd_themes["bar_arena_public_death"]	= {"ambient\\arena\\crowd_wave_1",
	                        "ambient\\arena\\crowd_wave_2",
	                        "ambient\\arena\\crowd_wave_3"
	                        }
ph_snd_themes["bar_arena_fight_1"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_ready"}
ph_snd_themes["bar_arena_fight_1_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_finish"}
ph_snd_themes["bar_arena_fight_2"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_ready"}
ph_snd_themes["bar_arena_fight_2_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_finish"}
ph_snd_themes["bar_arena_fight_3"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_ready"}
ph_snd_themes["bar_arena_fight_3_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_finish"}
ph_snd_themes["bar_arena_fight_4"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_ready"}
ph_snd_themes["bar_arena_fight_4_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_finish"}
ph_snd_themes["bar_arena_fight_5"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_ready"}
ph_snd_themes["bar_arena_fight_5_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_finish"}
ph_snd_themes["bar_arena_fight_6"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_ready"}
ph_snd_themes["bar_arena_fight_6_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_finish"}
ph_snd_themes["bar_arena_fight_7"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_ready"}
ph_snd_themes["bar_arena_fight_7_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_finish"}
ph_snd_themes["bar_arena_fight_8"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_ready"}
ph_snd_themes["bar_arena_fight_8_end"]	= {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_finish"}

ph_snd_themes["x18_sound_1"] = {"ambient\\x18\\x18_hit_8"}
ph_snd_themes["x18_sound_2"] = {"ambient\\x18\\x18_metal_2"}
ph_snd_themes["x18_sound_3"] = {"ambient\\x18\\x18_metal_3"}
ph_snd_themes["x18_sound_4"] = {"ambient\\x18\\x18_metal_4"}
ph_snd_themes["x18_sound_5"] = {"ambient\\x18\\x18_metal_5"}
ph_snd_themes["x18_sound_6"] = {"ambient\\x18\\x18_creak_2"}
ph_snd_themes["x18_sound_7"] = {"ambient\\x18\\x18_creak_1"}
ph_snd_themes["x18_sound_8"] = {"ambient\\x18\\x18_hit_7"}
ph_snd_themes["x18_sound_9"] = {"ambient\\x18\\x18_footsteps_2"}
ph_snd_themes["x18_sound_10"] = {"ambient\\x18\\x18_move_4"}
ph_snd_themes["x18_sound_11"] = {"ambient\\x18\\x18_footsteps"}
ph_snd_themes["x18_sound_12"] = {"ambient\\x18\\x18_move_3"}

ph_snd_themes["x16_engine1_run"] = {"ambient\\x16\\x16_engine1_run"}
ph_snd_themes["x16_engine1_stop"] = {"ambient\\x16\\x16_engine1_stop"}

ph_snd_themes["x16_engine2_run"] = {"ambient\\x16\\x16_engine2_run"}
ph_snd_themes["x16_engine2_stop"] = {"ambient\\x16\\x16_engine2_stop"}

ph_snd_themes["x16_hum_2"] = {"ambient\\x16\\x16_hum_2"}
ph_snd_themes["x16_switch_1"] = {"ambient\\x16\\switch_1"}
ph_snd_themes["x16_switch_2"] = {"ambient\\x16\\switch_2"}

ph_snd_themes["x18_firedoor"] = {"anomaly\\fireball_idle"}
ph_snd_themes["mon_poltergeist"] = {"anomaly\\anomaly_gravy_hit1"}

ph_snd_themes["psy_voices"] = {{[[characters_voice\scenario\yantar\psy_voices_1]]}} --' Стерео

ph_snd_themes["heli_explosion"] = {[[weapons\heli_explosion]]}

ph_snd_themes["trader_door_open_start"]		= {[[device\door_start]]}
ph_snd_themes["trader_door_close_start"]	= {[[device\door_closing]]}
ph_snd_themes["trader_door_close_stop"]		= {[[device\door_stop]]}
ph_snd_themes["trader_door_locked"]			= {[[device\door_locked]]}
ph_snd_themes["trader_door_unlock"]			= {[[device\door_servomotor]]}
ph_snd_themes["wood_small_open"]			= {[[device\wood_small_open]]}
ph_snd_themes["wood_small_close_start"]		= {[[device\wood_small_close_start]]}
ph_snd_themes["wood_small_close_stop"]		= {[[device\wood_small_close_stop]]}
ph_snd_themes["wood_large_open"]			= {[[device\wood_large_open]]}
ph_snd_themes["wood_large_close_start"]		= {[[device\wood_large_close_start]]}
ph_snd_themes["wood_large_close_stop"]		= {[[device\wood_large_close_stop]]}
ph_snd_themes["metal_small_open"]			= {[[device\metal_small_open]]}
ph_snd_themes["metal_small_close_start"]	= {[[device\metal_small_close_start]]}
ph_snd_themes["metal_small_close_stop"]		= {[[device\metal_small_close_stop]]}

-- HORROR-TIME sound themes
-- Фоновые звуки
ph_snd_themes["horror_background_1"]	= {
									[[soundtrack\horror_time\horror_background_1]],
									[[soundtrack\horror_time\horror_background_2]],
									[[soundtrack\horror_time\horror_background_3]],
									[[soundtrack\horror_time\horror_background_4]],
									[[soundtrack\horror_time\horror_background_5]],
									[[soundtrack\horror_time\horror_background_6]],
									[[soundtrack\horror_time\horror_background_7]],
									[[soundtrack\horror_time\horror_background_8]],
									[[soundtrack\horror_time\horror_background_9]],
									[[soundtrack\horror_time\horror_background_10]]
									}

-- Атмосферные звуки
ph_snd_themes["horror_snd_fx_1"]	= {
									[[soundtrack\horror_time\1]],
									[[soundtrack\horror_time\2]],
									[[soundtrack\horror_time\3]],
									[[soundtrack\horror_time\4]],
									[[soundtrack\horror_time\5]],
									[[soundtrack\horror_time\6]],
									[[soundtrack\horror_time\7]],
									[[soundtrack\horror_time\8]],
									[[soundtrack\horror_time\9]],
									[[soundtrack\horror_time\10]],
									[[soundtrack\horror_time\11]],
									[[soundtrack\horror_time\12]],
									[[soundtrack\horror_time\13]],
									[[soundtrack\horror_time\14]],
									[[soundtrack\horror_time\15]],
									[[soundtrack\horror_time\16]],
									[[soundtrack\horror_time\17]],
									[[soundtrack\horror_time\18]],
									[[soundtrack\horror_time\19]],
									[[soundtrack\horror_time\20]],
									[[soundtrack\horror_time\21]],
									[[soundtrack\horror_time\22]],
									[[soundtrack\horror_time\23]],
									[[soundtrack\horror_time\24]],
									[[soundtrack\horror_time\25]],
									[[soundtrack\horror_time\26]],
									[[soundtrack\horror_time\27]],
									[[soundtrack\horror_time\28]],
									[[soundtrack\horror_time\29]],
									[[soundtrack\horror_time\30]],
									[[soundtrack\horror_time\31]],
									[[soundtrack\horror_time\32]],
									[[soundtrack\horror_time\33]],
									[[soundtrack\horror_time\34]],
									[[soundtrack\horror_time\35]],
									[[soundtrack\horror_time\36]],
									[[soundtrack\horror_time\37]],
									[[soundtrack\horror_time\38]],
									[[soundtrack\horror_time\39]],
									[[soundtrack\horror_time\40]],
									[[soundtrack\horror_time\41]],
									[[soundtrack\horror_time\42]],
									[[soundtrack\horror_time\43]],
									[[soundtrack\horror_time\44]],
									[[soundtrack\horror_time\45]],
									[[soundtrack\horror_time\46]],
									[[soundtrack\horror_time\47]],
									[[soundtrack\horror_time\48]],
									[[soundtrack\horror_time\49]],
									[[soundtrack\horror_time\50]],
									[[soundtrack\horror_time\51]],
									[[soundtrack\horror_time\52]],
									[[soundtrack\horror_time\53]],
									[[soundtrack\horror_time\54]],
									[[soundtrack\horror_time\55]],
									[[soundtrack\horror_time\56]],
									[[soundtrack\horror_time\57]],
									[[soundtrack\horror_time\58]],
									[[soundtrack\horror_time\59]],
									[[soundtrack\horror_time\60]],
									[[soundtrack\horror_time\61]],
									[[soundtrack\horror_time\62]],
									[[soundtrack\horror_time\63]],
									[[soundtrack\horror_time\64]],
									[[soundtrack\horror_time\65]],
									[[soundtrack\horror_time\66]],
									[[soundtrack\horror_time\67]],
									[[soundtrack\horror_time\81]],
									[[soundtrack\horror_time\112]],
									[[soundtrack\horror_time\114]],
									[[soundtrack\horror_time\115]],
									[[soundtrack\horror_time\116]],
									[[soundtrack\horror_time\117]],
									[[soundtrack\horror_time\118]],
									[[soundtrack\horror_time\119]],
									[[soundtrack\horror_time\120]],
									[[soundtrack\horror_time\121]]
									}

-- Переговоры учёных по радио
ph_snd_themes["horror_radio_voise_1"]	= {
									[[soundtrack\horror_time\79]],
									[[soundtrack\horror_time\80]],
									[[soundtrack\horror_time\82]],
									[[soundtrack\horror_time\83]],
									[[soundtrack\horror_time\101]],
									[[soundtrack\horror_time\110]],
									[[soundtrack\horror_time\111]]
									}

-- Переговоры сталкеров по радио
-- Заблудились
ph_snd_themes["horror_radio_voise_2"]	= {
									[[soundtrack\horror_time\75]],
									[[soundtrack\horror_time\70]],
									[[soundtrack\horror_time\69]],
									[[soundtrack\horror_time\68]],
									[[soundtrack\horror_time\74]],
									[[soundtrack\horror_time\73]],
									[[soundtrack\horror_time\71]],
									[[soundtrack\horror_time\72]],
									[[soundtrack\horror_time\71]]
									}

-- Попали в аномалию
ph_snd_themes["horror_radio_voise_3"]	= {
									[[soundtrack\horror_time\76]],
									[[soundtrack\horror_time\77]],
									[[soundtrack\horror_time\78]],
									[[soundtrack\horror_time\71]],
									[[soundtrack\horror_time\72]],
									[[soundtrack\horror_time\71]]
									}

-- Зомби атакуют
ph_snd_themes["horror_radio_voise_4"]	= {
									[[soundtrack\horror_time\96]],
									[[soundtrack\horror_time\91]],
									[[soundtrack\horror_time\84]],
									[[soundtrack\horror_time\89]],
									[[soundtrack\horror_time\88]],
									[[soundtrack\horror_time\85]],
									[[soundtrack\horror_time\90]],
									[[soundtrack\horror_time\100]],
									[[soundtrack\horror_time\93]],
									[[soundtrack\horror_time\97]],
									[[soundtrack\horror_time\99]],
									[[soundtrack\horror_time\94]],
									[[soundtrack\horror_time\86]],
									[[soundtrack\horror_time\87]],
									[[soundtrack\horror_time\95]],
									[[soundtrack\horror_time\98]],
									[[soundtrack\horror_time\92]],
									[[soundtrack\horror_time\71]]
									}

-- Напали мутанты
ph_snd_themes["horror_radio_voise_5"]	= {
									[[soundtrack\horror_time\104]],
									[[soundtrack\horror_time\102]],
									[[soundtrack\horror_time\103]],
									[[soundtrack\horror_time\105]],
									[[soundtrack\horror_time\106]],
									[[soundtrack\horror_time\107]],
									[[soundtrack\horror_time\108]],
									[[soundtrack\horror_time\109]]
									}


ph_snd_themes["car_horn"] = {"characters_voice\\scenario\\car_horn"}


-- HORROR-TIME sound themes

-----------------------------------------------------------------------------------------------------------------------------------
--	Theme  functions
-----------------------------------------------------------------------------------------------------------------------------------
function weather_class(avail_types, npc)
	local type = "weather_good"
	if level.rain_factor() < 0.07 then
		type = "weather_good"
	else
		type = "weather_bad"
	end
	return type
end

function combat_class(avail_types, npc)
	if npc:best_enemy() ~= nil or
	   npc:best_danger() ~= nil
	then
		return ""
	end
	return "state"
end

-------------------------------------------------------------------------
-- ЗВУКИ СТАЛКЕРОВ
-------------------------------------------------------------------------
local sounds_base = stalker_ids.sound_script + 10000
function id()
	sounds_base = sounds_base + 1
	return sounds_base - 1
end

theme = {
	-- погода
	weather = {	exec = sound_theme.weather_class, 
				types = {weather_bad	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
						 weather_good	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}} }},

	-- состояния тела
	state = {	exec = sound_theme.combat_class, 
				types = {state	= {min_snd = 60, max_snd = 90, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}} },
	

	sleep				= {min_snd = 10, max_snd = 15, rnd = 75, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- просьба о помощи
	help				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see			= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see_tutor		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_heavy			= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_thanx			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy_shoot	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- окрик
	hail				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- ожидание
	wait				= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- speech
    speech				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    speech1				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    
	-- угрозы
	threat_weap			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_back			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_stop			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции
--	reac_hear				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_see				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_monstr		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_enemy			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_neutral		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
--	reac_crps_friend		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_nothing			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	reac_box				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_music				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_joke				= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- болтовня
	talk_hello				= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_hello_friend		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_bye				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_accept				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_reject				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_abuse				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции на юзание
	use_yes_fight			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_sleep			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_kamp			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_default			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_fight			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_sleep			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_weapon			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_default			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_abuse				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- бой
	fight_attack			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	zombied_fight_attack	= {min_snd = 5, max_snd = 10,rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_search			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- торговля
	trade_yes				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	trade_no				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на губной гармошке
	intro_music				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	harmonica				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на гитаре
	guitar					= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- шутки, прибаутки
	intro_joke				= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	joke					= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Истории
	story_01				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_cool_info", min = 1, max = 1},
								[3] = {theme = "story_reac_continue", min = 2, max = 3},
								[5] = {theme = "story_reac_laughter", type = "all"}}},
	story_02				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_yes", min = 1, max = 2},
								[3] = {theme = "story_reac_continue", min = 1, max = 1},
								[4] = {theme = "story_reac_action_right", min = 1, max = 1},
								[5] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[6] = {theme = "story_reac_continue", min = 1, max = 1},
								[7] = {theme = "story_reac_belief_story, story_reac_final_happy, story_reac_yes", min = 2, max = 4}}},											
	story_03				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_continue", min = 1, max = 1},
								[2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
								[3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_04				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_continue", min = 1, max = 1},
								[2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
								[3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_05				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[1] = {theme = "story_reac_advice_sceptic, story_reac_advice_support", min = 1, max = 1}}},
	story_06				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= {	[2] = {theme = "story_reac_continue", min = 1, max = 1},
								[3] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[4] = {theme = "story_reac_action_right", min = 1, max = 1},
								[5] = {theme = "story_reac_yes", min = 1, max = 1},
								[6] = {theme = "story_reac_disbelief_teller, story_reac_belief_story", min = 2, max = 3},
								[7] = {theme = "story_reac_cool_teller", min = 1, max = 1},
								[8] = {theme = "story_reac_wonder", min = 1, max = 1},
								[9] = {theme = "story_reac_disbelief_story, story_reac_belief_story, story_reac_yes", min = 2, max = 4}}},

	legend_01				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
								[2] = {theme = "story_reac_wonder, story_reac_disbelief_story", min = 1, max = 1},
								[3] = {theme = "story_reac_yes", min = 2, max = 3},
								[4] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_02				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
								[2] = {theme = "story_reac_disbelief_story", min = 1, max = 1},
								[3] = {theme = "story_reac_wonder", min = 1, max = 1},
								[4] = {theme = "story_reac_laughter", min = 1, max = 1},
								[5] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_03				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_cool_info", min = 1, max = 1},
								[2] = {theme = "story_reac_yes, story_reac_doubt", min = 2, max = 4}}},								
	legend_04				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_fear", min = 1, max = 1},
								[2] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
								
	legend_05				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
					depence	= { [1] = {theme = "story_reac_yes", min = 2, max = 3},
								[2] = {theme = "story_reac_doubt", min = 1, max = 1},
								[3] = {theme = "story_reac_disbelief_story, story_reac_belief_story", min = 2, max = 4}}},

	story_reac_action_right		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_action_wrong		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_sceptic	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_support	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_belief_story		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_continue			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_info		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_teller		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_story	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_teller	= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_doubt			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_fear				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_happy		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_tragic		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_laughter			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_old_story		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_uncertain		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_wonder			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_yes				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	

	-- УНИКАЛЬНЫЕ ТЕМЫ	
	-- Escape
	esc_tolik_help				= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_guard_camp				= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_raid			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_attack			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_victory			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_go				= {min_snd = 3, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fox_alert				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_to_wolf			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_to_lager			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_thanks			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_thanks				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_say_thanks			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_lager_killer			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_dialog			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_ready				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_direction_fire			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_bridge_soldiers			= {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_bandit_shustryi			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_help			= {min_snd = 5, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_radio				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_radio_1			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_raport			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_raport_radio	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_call			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fox_thanks				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_thanks			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
			
	-- Garbage DramMoment
	gar_dm_bandit_backoff1		= {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_backoff2		= {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_demand		= {min_snd = 8, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_no_money		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_help_me		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_thank_you		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	gar_hellcar_alarm			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_ambush			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_bandits_seryi			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_grey_grey				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_seryi_see_actor			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dolg_blokpost			= {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_direction_fire			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_to_battle		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_victory			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- DarkValley
	val_prisoner_captive_help_me    = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_come_here  = {min_snd = 4, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_open       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_thanx      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_call             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_jeer             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_guard_jeer              = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_gate_soldiers               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_chase_soldiers              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_opendoor_soldier            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_guards               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase1      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase2      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase3      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase1         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase2         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase3         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase4         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase5         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase6         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase7         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_dead                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_go_home         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_phrase_invite        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Pripyat
	pri_followers_leader_phrase1_1  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_2  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_3  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase1     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase2     = {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- DeadCity
	cit_doctor_start_dlg            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_end_dlg              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_jail_guard_sneer            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_base_guard                  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_base_guard_talk_to_actor2   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_jail_guard_sleep            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Agroprom
	agr_factory_soldiers		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	-- desertir
	agr_dont_shoot			= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_desertir_spam		= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_1		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_2		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_3		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    agr_stalker_help_4		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    agr_krot_thanks_2		= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_krot_fear			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_doctor_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
-- Radar

	-- Bar Rostok Duty Guards
	bar_dolg_base_guard_backoff		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_base_guard_no_talk		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_osvedomitel_hello		= {min_snd = 15, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello			= {min_snd = 2, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello_room		= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_leader_hello			= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Bar dolg guard
	bar_dolg_guard_stop				= {min_snd = 15, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_prohodi				= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_guard_busy				= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Bar dolg hangar bridge
	bar_dolg_hangar_bridge_hello	= {min_snd = 16, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	bar_guard_enter					= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	bar_guard_stop					= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      

	-- Bar dolg Petrenko
	bar_dolg_petrenko_hello			= {min_snd = 3, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Bar psyh
	bar_psycho_pain					= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_psycho_goodluck				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_barman_psycho				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_arena_public				= {min_snd = 5, max_snd = 7, rnd = 80, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Rostok volkodav
	rostok_volkodav_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	rostok_volkodav_talk_2						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Rostok kruglov
	rostok_kruglov_help_1                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_2                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_3                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_4                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_5                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_6                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    rostok_kruglov_torrid                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_1                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_2                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--yantar sounds
	yantar_professor_idle						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_actor						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_1							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_2							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_3							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_4			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_5			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_6			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_7			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_8			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_9			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_10			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_professor_brain_quest_bad_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_professor_brain_quest_bad_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_professor_brain_quest_good_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_professor_brain_quest_good_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_professor_brain_quest_good_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_1								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_2								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_3								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	test_mega_remark							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

    
    -- Brainlab sounds
    
    brainlab_system_message_1                   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    brainlab_system_message_2                   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    brainlab_system_message_3                   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    brainlab_system_message_4                   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    brainlab_system_message_5                   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

    abdul_pray                   = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    post_oficer2_talk                   = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    kolbasa_i_batony                   = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    rupor_idle                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    rupor_alarm                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    volk_help                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    hunter1_to_tirsa                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    hunter2_hello                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    car_horn                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    meat                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    buzz                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    skidan_radio_music                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    agr_nii_rupor_music                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    quit                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    vetryak_work                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    atp_matugalnik_idle                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    post_soldier10_arest_call                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    bomzh_hello                  = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dont_shoot                 = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    esc_radiostation                 = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dar_vagon_radio_music                 = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    x18_entrance_vmordu                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dar_suicider_woman_cry1                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dar_suicider_woman_cry2                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dezintegrator_work1                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dar_izlom_werwolf_talk1                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dar_izlom_werwolf_talk2                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    dog_bark                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    ventilyator_work                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    subject_psy_atack                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    x18_matugalnik_idle                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mushroom_colony_bul_bul                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   x18_matugalnik_pray                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   x18_matugalnik_alarm                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   x18_incubator_work                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   x18_incubator_alarm                = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   anomal_radio_music1               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   anomal_radio_music2               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   silence               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   bar_magnitofon_music               = {min_snd = 3, max_snd = 15, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music1               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music2               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music3               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music4               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music5               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music6               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music7               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music8               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music9               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   script_magnitofon_music10               = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   skidan_hello1				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   skidan_hello2				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   drunk				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
   moisha_hello				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
deadmask_scary_sound			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
rupor_sirena			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
yan_comander_burer_see	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
yan_sold_comander_alarm	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
yan_lost_camp_scaner_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
ros_rescuers_vmordu	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
mil_village_dedok_radio_music	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
mil_freak_panik1	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
mil_kazarma2mafon	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
rad_secret_talk_music	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
rad_abdul_actor_check	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
rad_trader_radio_music	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
rad_trader_radio_music2	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_detsad_radio_music	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_detsad_cry	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_agent_lider_speech1	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_agent_lider_speech2	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_agent_lider_speech3	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_agent_lider_speech4	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_agent_lider_speech5	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
goldsphere_overheat	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
general_scientist_goodbye	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
hermit_talk	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_well_sound	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_village_trap_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_village_music_box_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
fire_burns	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_village_radio_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_strange_snd1	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_strange_snd2	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
pri_strange_snd3	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_nature_snd1	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_nature_snd2	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell1	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell2	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell3	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell4	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell5	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell6	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell7	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell8	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
kontrab5_storytell9	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_base_radio_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_firest_magnitofon_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
marouder_to_search	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_base_chimera_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_courier_guard_speech	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
catwoman_help	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
catwoman_laught	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
predb_stoned_izlom_snd	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
hunter_7_help	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
mil_vsu_vmordu	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
flies	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
zombied_idle	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
















    -- Military sounds
    mil_max_thanx                  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_before_collect         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_kolyan                     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_kolyan              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_tolyan              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh1             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh2             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh3             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh4             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh5             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase1            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase2            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase3            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase4            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase5            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase6            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase7            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_crazy                      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_about_sniper          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_go_attack             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_patrol             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill1           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill2           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill3           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_zoneguard          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_patrol_base        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_khutor_attack          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_guard_to_max               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_lukash_to_guard            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_lukash_to_actor            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_paul_frost                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_killer                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_scull                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_actor               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrases            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_pavlik_to_ara              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_ara_to_pavlik              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_ara_ambush                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter1                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter2                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter3                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_getready              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_lukash_done           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush1            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush2            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush3            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush4            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush5            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush6            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory1           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory2           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory3           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory4           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory5           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_before_attack1        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}, 
    mil_dolg_before_attack2        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_fight                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_silent                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_cherep_hi                 = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}
}
   
--' В темах для игрока интервал задается в миллисекундах!!!
actor_theme = {
	level_border_detector = {min_snd = 10, max_snd = 100,
							 sounds = {xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_2]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_2]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_4]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_5]]),
									   xr_sound.get_safe_sound_object([[detectors\geiger_6]]) }}
}
   										
function select_sound_from_ltx(obj, section, ltx)
--	1. проверка по story_id
	local c = obj:story_id()
	if ltx:line_exist(section, utils.to_str(c)) then
		return ltx:r_string(section, utils.to_str(c))
	end

--	2. проверка по npc_profile
	c = obj:profile_name()
	if ltx:line_exist(section, c) then
		return ltx:r_string(section, c)
	end

--	3. проверка по character_community
	c = obj:character_community()
	if ltx:line_exist(section, c) then
		return ltx:r_string(section, c)
	end
	
--	4. загрузка дефолта
	if ltx:line_exist(section, "stalker") then
		return ltx:r_string(section, "stalker")
	else
		return nil
	end
end

-----------------------------------------------------------------------------------------------------------------------------------
local character_prefix = ""
local default_prefix = "characters_voice\\"
function check_prefix(s)
	local flag = string.sub(s, 1, 1)
	return flag, string.sub(s, 3)
end

function load_sound(obj)
	local k,v = 0,0
	
	-- загрузка звуков на основе данных ltx
	function load_sound_from_ltx(obj, name, tbl)		
		tbl.max_ids[obj:id()] = {}
		if snd_ini:section_exist(name.."_rnd") then		
			local s = select_sound_from_ltx(obj, name.."_rnd", snd_ini)			
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end
					
				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].rnd_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.rnd_id)

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(name.."_seq") then
			local s = select_sound_from_ltx(obj, name.."_seq", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end

				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].into_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.into_id)
				tbl.max_ids[obj:id()].into_cycled = true

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(name.."_single") then
			local s = select_sound_from_ltx(obj, name.."_single", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end

				--printf("NPC[%s] flag[%s] prefix[%s] path[%s]", obj:name(), flag, obj:sound_prefix(), path)
				tbl.max_ids[obj:id()].into_max = obj:add_sound(path, nstl, snd_type.talk, 2, 1, tbl.into_id)
				tbl.max_ids[obj:id()].into_cycled = false

				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end			
			end
		end
	end
	
	function load_theme_sound(npc, tbl)
		for k,v in pairs(tbl) do
			if v.types == nil then
				load_sound_from_ltx(npc, k, v)
			else
				load_theme_sound(npc, v.types)
			end
		end
	end

	load_theme_sound(obj, theme)

	-- делаем заготовку в db.sound
	db.sound[obj:id()] = {}
	
----	printf("All sounds loaded for %s, section %s", obj:name(), obj:section())
---	print_table(theme)
end